### ISSUE TITLE
Brak informacji o sposobie zgłaszania błędów bezpieczeństwa

### ISSUE THREAD

**Issue by scibi** [epforgpl/_mojePanstwo-Portal#183]
Na stronie nie ma informacji jak zgłaszać błędy bezpieczeństwa. Z oczywistych względów nie powinno się tego robić w publicznie dostępnym bugtrackerze githuba.

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish dodaj proszę

"Błędy bezpieczeństwa prosimy zgłaszać pod adresem mailowym security@mojepanstwo.pl" na https://mojepanstwo.pl/zglosblad

BTW: Do githuba można by linkować bezpośrednio do tworzenia issue: https://github.com/epforgpl/_mojePanstwo-Portal/issues/new
