### ISSUE TITLE
Powinny się wyświetlać błędy przy zmianie hasła

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-Portal#217]
Kod js: Plugin/Paszport/webroot/js/user-center.js
Trzeba obsłużyć status != 200

Możesz otrzymać status = 500, wtedy format:
data.alerts -> alerty do wyświetlenia (np. gdy stare hasło się nie zgadza)
{alerts: errors: ["cos sie zwalilo"]}

Lub status = 422 i wtedy się wyświetlają błędy poszczególnych pól:
{errors: password: ["za krótkie"], repassword: ["powtórzenie nie powtarza", "za krótkie"]}

- [ ] dopuszczamy możliwość nazwy użytkownika, która zawiera spacje i inne znaki specjalne (również na /register)

**Comment by Cain-Ish** [comment]
Nowy wygląd profilu nie obsługuje user-center.js
