### ISSUE TITLE
Brakuje województw w bazie, mimo że ich liczba jest prawidłowa

### ISSUE THREAD

**Issue by maksymilian-bogun** [epforgpl/_mojePanstwo-Portal#239]
http://mojepanstwo.pl/dane/wojewodztwa zwraca "Brak wyników"

podobnie http://api.mojepanstwo.pl/dane/dataset/wojewodztwa/search.json zwraca pusty wynik

**Comment by danielmacyszyn** [comment]
http://mojepanstwo.pl/moja_gmina/wojewodztwa
