### ISSUE TITLE
Link do wystąpień nie działa

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-Portal#302]
Będąc na stronie: http://mojepanstwo.pl/sejmometr

Nie działa przykładowo: http://mojepanstwo.pl/dane/poslowie/4/wystapienia

**Comment by danielmacyszyn** [comment]
W nowej wersji nie pokazujemy takiego adresu (aczkolwiek działa, dla kompatybilności). Prawidłowy link, osiągalny ze strony głównej posła to http://mojepanstwo.pl/dane/poslowie/4,ajchler-romuald?channel=1
