### ISSUE TITLE
Sejmometr- błąd w statystyce przy liczbie kobiet w Sejmie

### ISSUE THREAD

**Issue by Karo-ePF** [epforgpl/_mojePanstwo-Portal#304]
W sekcji: 'Posłanki i posłowie - Ilość kobiet i mężczyzn w Sejmie i w poszczególnych partiach', pierwszy wykres mówi 'Sejm RP: 82% i 25%'

**Comment by danielmacyszyn** [comment]
Poprawione. Pojawi się na produkcji dziś.
