### ISSUE TITLE
Twitter - zle formatowanie tekstow

### ISSUE THREAD

**Issue by Cain-Ish** [epforgpl/_mojePanstwo-Portal#312]
Wyniki z API Twittera czasami podaja zle dlugosci linkow badz hasttagów co kończy sie tworzeniem linków tylko na "polowie" hastaga badz linka.
Jednym z bledow jest to ze link podawany przez API jest linkiem skróconym, długość wyliczana jest tez rprzez link skócony natomiast wklejany tekst juz jest dłuższy co w momencie formatowania powoduje nadanie formatu link tylko na polowe znakow (rowna dlugosci skroconego tekstu)

**Comment by danielmacyszyn** [comment]
Poprawione w nowej wersji
