### ISSUE TITLE
Warstwa 'gmina' powiatu

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-Portal#340]
Np. http://api.mojepanstwo.pl/dane/powiaty/1?layers=gmina

Sprawdzić, gdzie jest wykorzystywane i:
- usunąć
- lub rzucać wyjątkiem, jeżeli to nie jest miasto na prawach powiatu

**Comment by danielmacyszyn** [comment]
W nowej wersji nie mamy takiej warstwy. Szukanie gmin w powiecie jest realizowane inaczej.
http://mojepanstwo.pl/dane/powiaty/1,aleksandrowski
