### ISSUE TITLE
Sejmometr: błędna liczba posłów na diagramie (106% zamiast 100%)

### ISSUE THREAD

**Issue by Karo-ePF** [epforgpl/_mojePanstwo-Portal#358]
W dziale 'Posłanki i posłowie -Ilość kobiet i mężczyzn w Sejmie' na pierwszym diagramie pokazujemy 80%+26% to razem 106%  http://mojepanstwo.pl/sejmometr#poslankiPoslowie

**Comment by danielmacyszyn** [comment]
Poprawione w nowej wersji
http://mojepanstwo.pl/sejmometr
