### ISSUE TITLE
KRS: pusty nip lub inne pola numeryczne oznaczane są zerem

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-Portal#361]
Intuicyjny byłby null.

http://api.mojepanstwo.pl/krs/podmioty/536154

**Comment by danielmacyszyn** [comment]
To wynika ze struktury bazy SQL. Na razie nie planujemy zmieniać - planujemy uaktualnić te dane z innych źródeł np, REGON.
