### ISSUE TITLE
Szukanie szablonów i adresatów

### ISSUE THREAD

**Issue by danielmacyszyn** [epforgpl/_mojePanstwo-Portal#368]
Podczas szukania, w prawej części inputa, powinien się wyświetlać loader

**Comment by Cain-Ish** [comment]
Nie podłączone JSON

**Comment by danielmacyszyn** [comment]
- [ ] color dla input:placeholder - #CCC 
- [ ] autocompleter na absolucie
- [ ] w autocompleter dla instytucji usunąć button "wybierz" - cały li jest klikalny i powoduje wybór
