### ISSUE TITLE
Edytor - ogólne

### ISSUE THREAD

**Issue by danielmacyszyn** [epforgpl/_mojePanstwo-Portal#375]
- [x] czasami zawartość świeżo utworzonego pisma znika z edytora, przy widoku /edit (nie wiem w jakich warunkach ten błąd występuje - przydarzył mi się kilka razy)
- [x] po zmianie szablonu dla istniejącego pisma powinien pojawić się confirm("Zmiana szablonu spowoduje zastąpienie treści pisma nowym szablonem. Czy na pewno chcesz to zrobić?") Toteż powinno się stać - po zmianie szablonu, usuwamy starą treścią i zastępujemy nową.
- [x] dla istniejącego pisma, w widoku /edit, przycisk "Wpisz treść pisma" powinien mieć tytuł "Wróć do edycji treści pisma" i klasę btn-default

**Comment by danielmacyszyn** [comment]
- [ ] Nie można edytować pola adresat
- [ ] W głównej (chyba nawet w żadnej) części edytora nie można wciśnąć ENTER, żeby przejść do nowej linii

**Comment by Cain-Ish** [comment]
Zmiana szablona powoduje pojawianie sie bootstrap popover
