### ISSUE TITLE
Ostrzeżenia przy opuszczaniu strony edytora

### ISSUE THREAD

**Issue by danielmacyszyn** [epforgpl/_mojePanstwo-Portal#381]
Jeśli pismo jest zapisane ($pismo['saved']=='1'), to przy opuszczaniu edytora dajemy: confirm("Czy chcesz opuścić tę stronę bez zapisywania zmian?")

Jeśli pismo nie jest zapisane ($pismo['saved']=='0'), to przy opuszczaniu edytora dajemy: confirm("Pismo nie zostało jeszcze zapisane. Czy na pewno nie chcesz go zapisać?")

**Comment by Cain-Ish** [comment]
Ogarnąć komunikaty. Są ustawione te co powinny ale przeglądarka wyświetla inne (o utracie niezapisanch danych podczas opuszcania strony wiec też może być w razie czego)

**Comment by Cain-Ish** [comment]
Błąd tylko w FF - nie pozwala na custom text
