### ISSUE TITLE
Zmiana nazwy pisma...

### ISSUE THREAD

**Issue by danielmacyszyn** [epforgpl/_mojePanstwo-Portal#382]
- [x] w requeście zapisującym dokleja do nazwy "Zapisz" (od guzika, który tam siedzi)
- [x] Nie da się anulować edycji (np po wciśnięciu Escape), obok "Zapisz", powinien być też guzik "Anuluj"
- [x] Wciśnięcie guzika "Zapisz" nie wychodzi z edycji

**Comment by Cain-Ish** [comment]
@danielmacyszyn co oznacza

**Comment by danielmacyszyn** [comment]
- [ ] Escape nadal nie wychodzi z edycji
- [ ] Przyciski "Zapisz" i "Anuluj" powinny być widoczne odrazu po wejściu w tryb edycji

**Comment by Cain-Ish** [comment]
[Enter] oraz [Escape] wychodza z edycji tytułu (pisma.js#153) - czy ma obejmować to jeszcze coś?
