### ISSUE TITLE
Link do MSiG w historii KRS-u

### ISSUE THREAD

**Issue by ad-m** [epforgpl/_mojePanstwo-Portal#386]
Hej,

http://mojepanstwo.pl/dane/krs_podmioty/63704,zaklad-wodociagow-kanalizacji/historia

Chciałbym mieć link do odpowiedniej podstrony Monitora Sądowego i Gospodarczego. Chce źródeł, bo watchdog ;-) Da radę?

Z wyrazami szacunku,

**Comment by danielmacyszyn** [comment]
@ad-m zmieniamy "historię" na "aktualności". 
Tutaj masz podgląd z "głębokiego ukrycia"
http://mojepanstwo.pl/dane/krs_podmioty/63704,zaklad-wodociagow-kanalizacji/aktualnosci

Nie jest jeszcze tak czytelne, jak chcemy, żeby było, ale pod każdym neswem masz link do MSiG

**Comment by ad-m** [comment]
Dziękuje. Przyda się. Przeszukiwanie MSiG ręcznie jest straszne…
