### ISSUE TITLE
Źle linkują zakładki w głosowaniach

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-Portal#387]
Przejście z http://mojepanstwo.pl/dane/sejm_posiedzenia_punkty/2014,

na debaty i głosowania powoduje 404
Chyba spowodowane pustym slugiem (link kończy przecinek, może w routes trzeba poprawić regexp)

**Comment by McCease** [comment]
Teraz chyba błąd nie występuje - możesz sprawdzić i ew. zamknąć issue?

**Comment by KrzysztofMadejski** [comment]
Jest ok
