### ISSUE TITLE
BDL - moduł Miejscowości

### ISSUE THREAD

**Issue by nirski** [epforgpl/_mojePanstwo-Portal#390]
Czy API do Banku Danych Lokalnych będzie będzie uwzględniało również moduł [Miejscowości](http://stat.gov.pl/bdl/app/dane_podgrup_m.indeks)? Obecnie [dane](http://mojepanstwo.pl/dane/bdl_wskazniki/41299) są dostępne jedynie do poziomu gminy.

**Comment by danielmacyszyn** [comment]
Teraz tego nie planujemy. Ale pod koniec kwietnia zaczynamy pracę nad nowym sposobem wyświetlania wskaźników BDL, we współpracy z Obserwatorium Żywej Kultury. Wtedy prawdopodobnie dodamy moduł miejscowości.

**Comment by nirski** [comment]
Czy został już dodany moduł Miejscowości?
