### ISSUE TITLE
zamówienia publiczne. nie działa filtr data publikacji

### ISSUE THREAD

**Issue by igor2901** [epforgpl/_mojePanstwo-Portal#391]
po wpisaniu dat od do wyświetla się pełna lista danych 
nie działa również filtr konkretnej daty

**Comment by Cain-Ish** [comment]
Witam,
Czy mowa  o stronie http://mojepanstwo.pl/zamowienia_publiczne ?

**Comment by igor2901** [comment]
tak

klucz wyświetlający zamówienia publiczne według data zdecydowanie ułatwiłby wyszukiwanie

**Comment by danielmacyszyn** [comment]
Poprawione. Można już wybierać zakres czasowy wyświetlanych danych. @MarekBielecki czy ten kalendarzyk ma podpięty jakiś styl, czy on tak po prostu wygląda? Trzeba w nim zrobić tak, żeby klikalne elementy (np dni) miały css cursor: pointer

**Comment by MarekBielecki** [comment]
Ma własny styl który znajduje się w app/webroot/plugins/bootstrap-datepicker/css - lokalnie wyświetla się dobrze, być może jquery-ui psuje te style i pewnie trzeba pozmieniać nazwy styli albo dodać jakiś przedrostek.

**Comment by igor2901** [comment]
Potwierdzam działa 
Można zamknąć ticket
Dzięki 

Wysłane z iPada

Dnia 10 kwi 2015 o godz. 12:40 danielmacyszyn <notifications@github.com> napisał(a):
