### ISSUE TITLE
Niekompletne dane KRS

### ISSUE THREAD

**Issue by ad-m** [epforgpl/_mojePanstwo-Portal#392]
Szanowni,

Dostępne na stronie (i poprzez API) dane KRS wydają się niekompletne. Na http://mojepanstwo.pl/dane/gminy/769,kety/ngo mamy 69 podmiotów, a w API mamy ich ~42
```
In [9]: requests.get('http://api.mojepanstwo.pl/dane/dataset/krs_podmioty/search.json', params={'conditions[gmina_id]': '769', 'conditions[rejestr]': '2'}).json()['search']['pagination']['total']
Out[9]: 42
```
To jest dziwna rozbieżność. Według http://www.nowa-wies-kety.pl/wykaz-organizacji-pozarzadowych-w-gminie-kety/#comment-1471 (ems mi nie działa teraz) w KRS-ie dla Kęt jest 56 podmiotów.

**Comment by danielmacyszyn** [comment]
Pole 'rejestr' nie oznacza dokładnie, czy jakiś podmiot jest NGO, czy
biznesem, ponieważ są NGOsy, które prowadzą działalność gospodarczą i są
wpisane do rejestru przedsiębiorców.
Rozbieżności mogą wynikać też z przyjętej metodologii, co jest NGOsem, a co
biznesem.

Odpisy z KRS zawierają pole "Forma prawna". To są wszystkie, różne formy
prawne, które wyciągnęliśmy z całego KRS:

"1","FUNDACJA","2"
"2","INSTYTUT BADAWCZY","2"
"3","IZBA GOSPODARCZA","2"
"4","IZBA RZEMIEŚLNICZA","2"
"5","KÓŁKO ROLNICZE","2"
"6","ODDZIAŁ ZAGRANICZNEGO PRZEDSIĘBIORCY","1"
"7","PRZEDSIĘBIORSTWO PAŃSTWOWE","1"
"8","ROLNICZE ZRZESZENIE BRANŻOWE","2"
"9","SPÓŁDZIELNIA","2"
"10","SPÓŁKA AKCYJNA","1"
"11","SPÓŁKA JAWNA","1"
"12","SPÓŁKA KOMANDYTOWA","1"
"13","SPÓŁKA PARTNERSKA","1"
"14","SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ","1"
"15","STOWARZYSZENIE","2"
"16","STOWARZYSZENIE KULTURY FIZYCZNEJ","2"
"17","ZWIĄZEK PRACODAWCÓW","2"
"18","ZWIĄZEK ZAWODOWY","2"
"19","CECH RZEMIEŚLNICZY","2"
"20","ZWIĄZEK SPORTOWY","2"
"21","OGÓLNOKRAJOWY ZWIĄZEK MIĘDZYBRANŻOWY","2"
"22","ZWIĄZKI ROLNIKÓW, KÓŁEK I ORGANIZACJI ROLNICZYCH","2"
"23","STOWARZYSZENIE KULTURY FIZYCZNEJ O ZASIĘGU OGÓLNOKRAJOWYM","2"
"24","ZRZESZENIE HANDLU I USŁUG","2"
"25","ZWIĄZEK STOWARZYSZEŃ","2"
"26","ZRZESZENIE TRANSPORTU","2"
"27","POLSKI ZWIĄZEK SPORTOWY","2"
"28","ZWIĄZEK ROLNICZYCH ZRZESZEŃ BRANŻOWYCH","2"
"29","ZWIĄZEK ZAWODOWY ROLNIKÓW INDYWIDUALNYCH","2"
"30","OGÓLNOKRAJOWE ZRZESZENIE MIĘDZYBRANŻOWE","2"
"31","FEDERACJA / KONFEDERACJA ZWIĄZKÓW PRACODAWCÓW","2"
"32","SPÓŁKA KOMANDYTOWO-AKCYJNA","1"
"33","OGÓLNOKRAJOWA REPREZENTACJA ZRZESZEŃ HANDLU I USŁUG","2"
"34","KOŚCIELNA OSOBA PRAWNA BĘDĄCA ORGANIZACJĄ POŻYTKU PUBLICZNEGO","2"
"35","INNA OSOBA PRAWNA BĘDĄCA ORGANIZACJĄ POŻYTKU PUBLICZNEGO","2"
"36","NIE POSIADAJĄCA OSOBOWOŚCI PRAWNEJ INSTYTUCJA KOŚCIELNA BĘDĄCA
ORGANIZACJĄ POŻYTKU PUBLICZNEGO","2"
"37","NIE POSIADAJĄCA OSOBOWOŚCI PRAWNEJ ORGANIZACJA POŻYTKU
PUBLICZNEGO","2"
"38","SPÓŁKA EUROPEJSKA","1"
"39","SAMODZIELNY PUBLICZNY ZAKŁAD OPIEKI ZDROWOTNEJ","3"
"40","JEDNOSTKA BADAWCZO-ROZWOJOWA","2"
"41","KOLUMNA TRANSPORTU SANITARNEGO","2"
"42","TOWARZYSTWO UBEZPIECZEŃ WZAJEMNYCH","1"
"43","ZWIĄZEK RZEMIOSŁA POLSKIEGO","2"
"44","GŁÓWNY ODDZIAŁ ZAGRANICZNEGO ZAKŁADU UBEZPIECZEŃ","1"
"45","OGÓLNOKRAJOWA REPREZENTACJA ZRZESZEŃ TRANSPORTU","2"
"46","INSTYTUCJA GOSPODARKI BUDŻETOWEJ","1"
"47","SPÓŁDZIELCZA KASA OSCZĘDNOŚCIOWO-KREDYTOWA","1"
"48","SPÓŁDZIELCZA KASA OSZCZĘDNOŚCIOWO-KREDYTOWA","1"

Następnie te wszystkie formy prawne podzieliliśmy na 3 typy:
1 - Biznes
2 - NGO
3 - Samodzielne, publiczne zakłady opieki zdrowotnej

W powyższej tabelce odpowiada za to trzecia kolumna. Jak widzisz, w
kategorii NGO, wylądowały takie formy prawne jak fundacje i stowarzyszenia,
ale też np. izby gospodarcze, izby rzemieślnicze, związki sportowe i kupa
innych rzeczy. W sumie teraz widzę, że niektóre mapowania są
kontrowersyjne, np "KOLUMNA TRANSPORTU SANITARNEGO". Może chciałbyś pomóc
poprawić to mapowanie (zaproponować zmiany)? ;)
Czy celowe byłoby wyprowadzenie tych wszystkich form prawnych jako dataset?

Żeby szukać po konkretnych formach prawnych, użyj pola [forma_prawna_id].
Żeby szukać po typach form prawnych (te trzy wymienione) - użyj pola
[forma_prawna_typ_id].




2015-02-25 12:41 GMT+01:00 Adam Dobrawy <notifications@github.com>:

> Szanowni,
>
> Dostępne na stronie (i poprzez API) dane KRS wydają się niekompletne. Na
> http://mojepanstwo.pl/dane/gminy/769,kety/ngo mamy 69 podmiotów, a w API
> mamy ich ~42
>
> In [9]: requests.get('http://api.mojepanstwo.pl/dane/dataset/krs_podmioty/search.json', params={'conditions[gmina_id]': '769', 'conditions[rejestr]': '2'}).json()['search']['pagination']['total']
> Out[9]: 42
>
> To jest dziwna rozbieżność. Według
> http://www.nowa-wies-kety.pl/wykaz-organizacji-pozarzadowych-w-gminie-kety/#comment-1471
> (ems mi nie działa teraz) w KRS-ie dla Kęt jest 56 podmiotów.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/epforgpl/_mojePanstwo-Portal/issues/392>.
>



-- 
Daniel Macyszyn
Prezes Zarządu, Fundacja ePaństwo
CEO, ePF
daniel.macyszyn@epf.org.pl
+48 505 118 287

Fundacja ePaństwo // ePF
ul. Nowogrodzka 25/39
00-021 Warszawa, Polska / Poland
www.epf.org.pl

**Comment by ad-m** [comment]
Część organizacji pozarządowych (nie wchodząc w szczegóły) mamy wyłącznie w rejestrze "Stowarzyszenia, inne organizacje społ. i zawodowe, fundacje, ZOZ", a część w "Stowarzyszenia, inne organizacje społ. i zawodowe, fundacje, ZOZ" oraz "Przedsiębiorcy". Przez warunek "'conditions[rejestr]': '2'" miałem nadzieje na uzyskanie zestawienia podmiotów w "Stowarzyszenia, inne organizacje społ. i zawodowe, fundacje, ZOZ" niezależnie od ewentualnego wpisu w ""Przedsiębiorcy". 

W jaki sposób to osiągnąć?

**Comment by danielmacyszyn** [comment]
Jadę pociągiem i mam bardzo słaby Internet - ciężko mi to teraz zbadać. Postaram się jutro - ewentualnie przez weekend.

**Comment by danielmacyszyn** [comment]
Pole 'rejestr' ma następujące znaczenie:
Domyślnie ma wartość 0
Jeśli w nagłówku odpisu z KRS występuje fraza "z rejestru przedsiębiorców", to rejestr = 1
Jeśli w nagłówku odpisu z KRS występuje fraza "z rejestru stowarzyszeŃ, innych organizacji spoŁecznych i zawodowych", to rejestr = 2

Dodatkowo:
Jeśli w nagłówku odpisu występuje fraza "podmiot wpisany także do rejestru stowarzyszeń, innych organizacji", to pole rejestr_stowarzyszen = 1

Jeśli w nagłówku odpisu występuje fraza "podmiot niewpisany do rejestru przedsiĘbiorcÓw', to nieprzedsiebiorca = 1

Także jest to dosyć skomplikowane i nie wiem, czy można polegać na tym polu. Lepiej chyba polegać na tym, co opisałem powyżej, czyli polu [forma_prawna_typ_id].
