### ISSUE TITLE
KRS 

### ISSUE THREAD

**Issue by kdudek89** [epforgpl/_mojePanstwo-Portal#393]
Witam,

Request do  http://api.mojepanstwo.pl/krs?q=impel

zwraca mi akty prawne 
""krakow_dzielnice_uchwaly.sesja_numer":"LIII","krakow_dzielnice_uchwaly.data_wydania":"2104-0"

**Comment by danielmacyszyn** [comment]
Witam,

Przechodzimy obecnie na wersję 2 serwera api. Dokumentacja pojawi się wkrótce. Tymczasem, jeśli chce Pan szukać informacji z KRS, to proszę zajrzeć tutaj: http://mojepanstwo.pl/krs i podejrzeć zawartość linku "API".

Pozdrawiam
