### ISSUE TITLE
Kancelaria Prawna Invictus sp. z o.o.

### ISSUE THREAD

**Issue by ArturSkrzypczyk** [epforgpl/_mojePanstwo-Portal#396]
Witam serdecznie

Proszę Państwa o uaktualnie danych firmy Kancelaria Prawna Invictus sp. z o.o. ( KRS: 0000253344).
Ja ani Piotr  nie jesteśmy od kilku miesięcy wspólnikami w spółce oraz jej nie rezprezentujemy - nie jesteśmy w Zarządzie. 

W państwa serwisie cały czas mylnie są zamieszczone nasze dane.

W razie pytań jestem do dyspozycji

Pozdrawiam
AS

**Comment by danielmacyszyn** [comment]
Poprawiono aktualizacje informacji o powiązaniach w KRS
