### ISSUE TITLE
Błędny link do github'a na podstronie 'oportalu'

### ISSUE THREAD

**Issue by sobi3ch** [epforgpl/_mojePanstwo-Portal#397]
Na podstronie http://mojepanstwo.pl/oportalu w tekscie *(..). Kod źródłowy oraz system zgłaszania błędów i propozycji (issues) dostępny jest w serwisie GitHub w postaci trzech repozytoriów: (..)* link GitHub to `https://https//github.com/epforgpl` zamiast `https://github.com/epforgpl`

**Comment by Cain-Ish** [comment]
Fix wysłany - na produkcji pojawi się niedługo. Dziękuje za zgłoszenie

**Comment by sobi3ch** [comment]
Nie ma sprawy.
