### ISSUE TITLE
Bład 500 podczas rejestracji

### ISSUE THREAD

**Issue by alchemyx** [epforgpl/_mojePanstwo-Portal#400]
Podczas rejestracji - czy to przez facebooka czy poprzez maila, pojawia się błąd 500.
![screenshot-mojepanstwo pl 2015-04-02 22-52-07](https://cloud.githubusercontent.com/assets/3201201/6973413/eed98ddc-d98a-11e4-980a-3333de36fd86.png)

**Comment by danielmacyszyn** [comment]
Poprawione przy rejestracji e-mail
@MarekBielecki upewnij się, że działa przez FB

**Comment by alchemyx** [comment]
Potwierdzam prawidłową rejestrację przez e-mail.

**Comment by MarekBielecki** [comment]
Już działa również dla FB
