### ISSUE TITLE
404 when writing to a municipality

### ISSUE THREAD

**Issue by michalskop** [epforgpl/_mojePanstwo-Portal#401]
I got 404 error when trying to write to a municipality:
1. http://mojepanstwo.pl/pisma
2. selecting Urzad miasta Kudowa-Zdroj
3. writing here: http://mojepanstwo.pl/pisma/nz20h/edit
4. "Zapisz"
5. http://mojepanstwo.pl/pisma/nz20h, gives the 404 error

**Comment by danielmacyszyn** [comment]
@michalskop I can't reproduce your error. I was able to successfully create a letter to this municipality. Could you confirm it or give more details?

**Comment by michalskop** [comment]
@danielmacyszyn I am getting this:
http://s28.postimg.org/r6m3m3hpp/mp1.jpg
http://s14.postimg.org/6f662znox/mp2.jpg

**Comment by danielmacyszyn** [comment]
There was a bug, creating letters, without a template specified. This was fixed. Sorry for an innocence.
