### ISSUE TITLE
Niaktualne dane

### ISSUE THREAD

**Issue by Enrique8** [epforgpl/_mojePanstwo-Portal#409]
Witam ,

po przejrzeniu Państwa serwisu internetowego  www.mojepanstwo.pl stwierdzam , iż dane w nim zawarte  , a dotyczące moich powiązań z firma  Laureola sp. z o.o.  są nieaktualne , dodatkowo komplikuje mi to uzyskanie kredytu w banku . Dlatego też proszę o pilną aktualizację oraz kontakt za mną pod nr 502552165 . W przypadku braku reakcji będę zmuszony podjąć inne kroki

pozdrawiam i proszę o pilny kontakt

Henryk Ratkowski

**Comment by danielmacyszyn** [comment]
Witam,
Kontaktujemy się z Panem prywatnie.
Pozdrawiam
Daniel Macyszyn
