### ISSUE TITLE
Layout dokumentacji API

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-Portal#413]
Tak to wyglądało kiedyś i taki content powinien pozostać:
https://web.archive.org/web/20150315070947/http://mojepanstwo.pl/api

Powinien dojść przycisk wyboru wersji API (v2, v3), której dotyczy dokumentacja.

Zostaje jedna strona (z sekcjami) opisująca API: https://web.archive.org/web/20150321154246/http://mojepanstwo.pl/api/technical_info

Poza tym interaktywne dokumentacje #412 poszczególnych API.

Pytanie czy tą stronę zrobić bardziej w stylu:
![mp_images](https://cloud.githubusercontent.com/assets/849975/7235040/cf99d4d6-e78b-11e4-8f5c-931b2e3db7b4.png)

czy

![like_main](https://cloud.githubusercontent.com/assets/849975/7235164/96ba0f18-e78c-11e4-8b22-588d9776a795.png)

Na drugim zajebiście by wyglądało interaktywna dokumentacja  #412, ale tekst słabo. Pomysły?

**Comment by danielmacyszyn** [comment]
@KrzysztofMadejski  Narazie mamy jedną obowiązującą wersję API - v2 i tylko do tego róbmy.
Jeśli chodzi o layout, to zróbmy to standardowo - czyli standardowy header apki i reszta (dół) na szarym tle, korzystając z podstawiwych styli portalu.

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish prośba o zmodyfikowanie http://mojepanstwo.pl/api
- [ ] zrobienie standardowego headera, takiego jak http://mojepanstwo.pl/media
  - [ ] umieszczenie go w pliku bazowym, na którym będzie się opierać `view` i `technical_info`
  - [ ] niech tytuł headera i podpis będzie można zmieniać w plikach dziedziczących (view i technical_info)
  - [ ] zrobienie menu zawierającego na sztywno (na razie) pozycje: Opis Techniczny, KRS, Statystyki
