### ISSUE TITLE
Problem z wyświetlaniem dokumentu

### ISSUE THREAD

**Issue by danielmacyszyn** [epforgpl/_mojePanstwo-Portal#415]
http://mojepanstwo.pl/dane/prawo/49608,ustawa-systemie-oswiaty

- [ ] Nie ma tekstu
- [x] Toolbar dokumentu jest nieprawidłowo ustawiony

**Comment by Cain-Ish** [comment]
Document zaczął działać więc nie mam jak odtworzyć problem
