### ISSUE TITLE
Podgląd dokumentów

### ISSUE THREAD

**Issue by danielmacyszyn** [epforgpl/_mojePanstwo-Portal#421]
http://www.awesomescreenshot.com/image/129194/435d8c4873ea9d87a92d268894bb0d21
http://mojepanstwo.local/dane/gminy/903,krakow/radni/39270

Usunąć biały pasek z krzyżykiem w górnej części podglądu. Krzyżek zamykający przenieść na prawo od przycisku "Pobierz dokument"

**Comment by Cain-Ish** [comment]
. Guzik zakmniecia nie moze zostac dodany do contentu jako ze zawartość jest w iframe zatem guziak zakmniecia w iframe nie zamykał by modal w parent.
Dodatkowo szerokosc strony jest dynamiczna (w zaleznosci czy jest czy nie slider obok)
