### ISSUE TITLE
Strony logowania / rejestracji

### ISSUE THREAD

**Issue by danielmacyszyn** [epforgpl/_mojePanstwo-Portal#425]
/login
/register
/forgot

- [x] doprowadzić okienka z treścią do jednakowego stylu, wzorowanego na /login (te same style inputów, napisów, przycisków, odstępów, itp...)
- [x] dodać tło - takie samo jak na stronie startowej portalu
- [x] poprawić środkowanie okienek - na wszystkich stronach powinno być środkowane wertykalnie i horyzontalnie - z uwzględnieniem bocznego headera portalu (który przy odpowiednim małym ekranie pokazuje się u góry)

**Comment by Cain-Ish** [comment]
Rejestracja
Usuwamy typ konta (ukryty input osoba)
Usuwamy jezyk storny (inout polski)
Dodanie logowanie/rejestracja przez facebook

Ogólna
Top: 45%
