### ISSUE TITLE
Strona główna PK

### ISSUE THREAD

**Issue by danielmacyszyn** [epforgpl/_mojePanstwo-Portal#428]
http://mojepanstwo.pl/przejrzysty_krakow

- [x] Główną szukajkę podłączyć pod http://przejrzystykrakow.pl/?q=
- [x] Główna szukajka ma jakieś nieprzyjemne obramowanie, którego nie ma na głównej szukajce mojepanstwo.pl
- [x] Ikonki aplikacji
1. Aktualności /
2. Rada Miasta /rada
3. Proces legislacyjny /druki
4. Radni Miasta /radni
5. Urząd Miasta /urzad
6. Dzielnice /dzielnice

**Comment by ArekSoldon** [comment]
Aktualnosci - zostają
rada miasta - zostaje
urząd - zostaje

https://dl.dropboxusercontent.com/u/19244622/kons.zip
