### ISSUE TITLE
Powiadomienia PK

### ISSUE THREAD

**Issue by danielmacyszyn** [epforgpl/_mojePanstwo-Portal#429]
- [ ] poprawić błąd http://mojepanstwo.local/powiadomienia/jak_to_dziala polegający na przeskakiwaniu stacji

Zbudować stronę http://mojepanstwo.local/dane/gminy/903,krakow/powiadomienia, analogiczną jak http://mojepanstwo.local/powiadomienia/jak_to_dziala, ale składającą się z następujących działów:

- [x] Dane publiczne z Krakowa
- [x] Prace Rady Miasta
- [x] Proces legislacyjny
- [x] Prace Urzędu Miasta Krakowa
- [x] Dzielnice Krakowa

**Comment by ArekSoldon** [comment]
![legislacja](https://cloud.githubusercontent.com/assets/3994690/7344193/e21d883a-ecc9-11e4-8dd1-17f09e0e48df.jpg)
![dzielnice](https://cloud.githubusercontent.com/assets/3994690/7344194/e21fadc2-ecc9-11e4-8d2f-ee8e9b3821b4.jpg)
![danepubliczne](https://cloud.githubusercontent.com/assets/3994690/7344192/e21d7d22-ecc9-11e4-82bc-a7386992b9bc.jpg)
![radamiasta](https://cloud.githubusercontent.com/assets/3994690/7344191/e21cff50-ecc9-11e4-9b63-d4421d98bdb1.jpg)
![urzadmiasta](https://cloud.githubusercontent.com/assets/3994690/7344247/45e50bd6-ecca-11e4-8fe6-8de7b40e06ee.jpg)

**Comment by ArekSoldon** [comment]
Od góry bo git psuje nazwy:
- legislacja
- dzielnice
- dane publiczne
- rada miasta 
- urzad miasta
