### ISSUE TITLE
Piechart - left align

### ISSUE THREAD

**Issue by danielmacyszyn** [epforgpl/_mojePanstwo-Portal#435]
http://mojepanstwo.local/dane/gminy/903,krakow/rada?channel=3

**Comment by MarekBielecki** [comment]
Wykresy w ogóle się nie pojawiają zarówno na dev jak i na produkcji (http://mojepanstwo.pl/dane/gminy/903,krakow/rada?channel=3) - konsola wyrzuca "ReferenceError: google is not defined". Błąd występuje chyba tylko w tej aplikacji (dane/gminy) np. w KRS działają prawidłowo.

**Comment by danielmacyszyn** [comment]
@Cain-Ish czy modyfikacje headerów mogły wypiąć ten skrypt?

**Comment by Cain-Ish** [comment]
@danielmacyszyn to znowu błąd compresora css/js - na dev z wyłączona opcją działa poprawnie.

**Comment by Cain-Ish** [comment]
@danielmacyszyn błąd powstał z powodu źle inicjalizowanych kodów JS (zła kolejność), nie sprawdzania czy dany obiekt w ogóle istnieje czy sprawdzanie czy biblioteka google.map istnieje.
Zmiany są twoje z października/listopada 2014 więc stawiam również na zmiane struktury po drodze
