### ISSUE TITLE
Mobile: pasek menu przy scrollowaniu się przesuwa

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-Portal#439]
I chowa się tam ikonka wyszukiwania

![screenshot_2015-04-24-19-31-17](https://cloud.githubusercontent.com/assets/849975/7369763/cd343590-edb4-11e4-91d6-470f745811a0.png)

**Comment by danielmacyszyn** [comment]
@Cain-Ish Można zamknąć?
