### ISSUE TITLE
Niedziałający link do pism

### ISSUE THREAD

**Issue by testarmy** [epforgpl/_mojePanstwo-Portal#444]
- Kategoria: Usability
- Powtarzalność: Zawsze
- Ważność: Drobny
- Priorytet: Normal
- Platforma, system, wersja: Chrome 42.0.2311.90, Windows 7
- Opis: Wygenerowany link do dokumentu jest nieaktywny. Brak możliwości skopiowania linka do schowka.
- Kroki do powtórzenia: 1. Uruchom stronę główną http://mojepanstwo.pl/ 2. Kliknij [Napisz pismo] 3. Wybierz dowolny szablon i kliknij [Stwórz pismo] 4. Napisz pismo i zapisz je [Zapisz] 5. Wybierz opcję: "Kliknij,aby udostępnić to pismo publicznie". 6. Powinien zostać wygenerowany "Link do dokumentu"
![id 4 niedzialajacy link do dokumentu_pisma](https://cloud.githubusercontent.com/assets/11860622/7390988/84318194-ee7d-11e4-901b-274529eb821b.png)

**Comment by danielmacyszyn** [comment]
@Cain-Ish 
- [ ] poprawć kopiowanie linku do schowka
- [ ] link do udostęniania - bez textTransform upper
- [ ] tło przycisku zmiany dostępu - przeźroczyste

**Comment by Cain-Ish** [comment]
Kopiowanie nie działało z powodu błędnego działania compilatora na produkcji - poprawiono.
