### ISSUE TITLE
Błędnie wyświetlane logo na stronie głównej

### ISSUE THREAD

**Issue by testarmy** [epforgpl/_mojePanstwo-Portal#445]
- Kategoria: Sugestia
- Powtarzalność: Zawsze
- Ważność: Drobny
- Priorytet: Normal
- Platforma, system, wersja: systemowa przeglądarka "Internet" Android 4.2.2 HTC PJ46100 
- Opis: Logo na stronie głównej jest zniekształcone.
- Kroki do powtórzenia: 1. Uruchom stronę główną. 
![id 5 logo znieksztalcone](https://cloud.githubusercontent.com/assets/11860622/7391031/e578f81a-ee7d-11e4-8941-d1b861dedd06.png)

**Comment by danielmacyszyn** [comment]
@Cain-Ish Można zamknąć?
