### ISSUE TITLE
Brak ikon [Szukaj] i [Aplikacje] w menu wysywanym pasku z lewej strony

### ISSUE THREAD

**Issue by testarmy** [epforgpl/_mojePanstwo-Portal#446]
- Kategoria: Sugestia
- Powtarzalność: Zawsze
- Ważność: Drobny
- Priorytet: Normal
- Platforma, system, wersja: systemowa przeglądarka "Internet" Android 4.2.2 HTC PJ46100 
- Opis: Brak ikon  [Szukaj] i [Aplikacje]  w menu, wysywanym pasku z lewej strony
- Kroki do powtórzenia: 1. Uruchom stronę główną. 2. Wysun menu z lewej strony.
![id 6 brak ikon](https://cloud.githubusercontent.com/assets/11860622/7391072/494e944e-ee7e-11e4-98f4-e7e2ac960401.png)

**Comment by danielmacyszyn** [comment]
Poprawiono
