### ISSUE TITLE
Tło strony głównej odbiega od tonacji reszty stron

### ISSUE THREAD

**Issue by testarmy** [epforgpl/_mojePanstwo-Portal#448]
- Kategoria: Sugestia
- Powtarzalność: Zawsze
- Ważność: Drobny
- Priorytet: Normal
- Platforma, system, wersja: Chrome 42.0.2311.90, Windows 7
- Opis: Tapeta strony głównej sugeruje tematykę inną niż właściwa zawartość portalu
- Kroki do powtórzenia: Uruchom stronę główną.

**Comment by danielmacyszyn** [comment]
Zmieniono tapety. Planowana możliwość samodzielnego ustawienia tapety.
