### ISSUE TITLE
Ucięte wyrazy w legendach wykresów

### ISSUE THREAD

**Issue by testarmy** [epforgpl/_mojePanstwo-Portal#456]
- Kategoria: GUI
- Powtarzalność: Zawsze
- Ważność: Poprawka
- Priorytet: Normal
- Platforma, system, wersja: Chrome 42.0.2311.90, Windows 7
- Opis: W legendach wielu wykresów można spotkać niekompletne frazy. Nie są one dokończone tylko wykropkowane. Przykład w załączniku.
- Kroki do powtórzenia: 1. Uruchom stronę główną http://mojepanstwo.pl/ 2. Kliknij [Wszystkie apliakcje] a następnie [Moja gmina] 3. Kliknij [Miejscowości]

![id16](https://cloud.githubusercontent.com/assets/11860622/7410776/67c85ff4-ef32-11e4-8215-a5ad1bab2ffc.png)

**Comment by Cain-Ish** [comment]
Naprawiono wraz ze zmianą silnika
