### ISSUE TITLE
Problem z usunięciem pisma urzędowego 

### ISSUE THREAD

**Issue by testarmy** [epforgpl/_mojePanstwo-Portal#459]
- Kategoria: Techniczny
- Powtarzalność: Zawsze
- Ważność: Ważny
- Priorytet: Normal
- Platforma, system, wersja: Chrome 42.0.2311.90, Windows 7
- Opis: Po stworzeniu nowego pisma a następnie usunięciu go, pismo nadal jest widoczne. Kliknięcie na nie skutkuje komunikatem o treści: To pismo nie istnieje lub nie masz do niego dostępu. Natomiast próba usunięcia go poprzez zaznaczenie checkbox'a skutkuje błędem 404. 
- Kroki do powtórzenia: 1. Uruchom stronę główną http://mojepanstwo.pl/ 2. Kliknij [Napisz pismo] a następnie [Stwórz pismo] 3. Kliknij [Zapisz] 4. Kliknij [Więcej] a następnie [Skasuj] 5. Aktualny rezultat: Pismo jest wciąż widoczne

**Comment by danielmacyszyn** [comment]
Poprawiono
