### ISSUE TITLE
Brak stronicowania wyników z "moja gmina"

### ISSUE THREAD

**Issue by testarmy** [epforgpl/_mojePanstwo-Portal#463]
- Kategoria: Usability
- Powtarzalność: Zawsze
- Ważność: Drobny
- Priorytet: Normal
- Platforma, system, wersja: Chrome 42.0.2311.90, Windows 7
- Opis: Brak możliwości zmiany sposobu wyświetlania wyników wyszukiwania dla wybranej gminy; brak stronicowania
- Kroki do powtórzenia: 1. Przejdź do [Wszystkie aplikacje /Moja gmina ] 2.Wybierz dowolną gminę wybierając województwo, powiat i gminę z menu z lewej strony lub bezpośrednio wpisując nazwę w pole do wyszukiwania 3 Wynik wyszukiwania dla "Wrocław" zawiera dużą liczbę dokumentów bez możliwości stronicowania. http://mojepanstwo.pl/dane/gminy/2347,wroclaw

**Comment by McCease** [comment]
Zmiana wyglądu sprawiła, że błąd jest nieaktualny.
