### ISSUE TITLE
Znikają dane w polu Adresat przy tworzeniu pisma, po przejściu na button "Stwórz pismo" za pomocą "TAB" na klawiaturze.

### ISSUE THREAD

**Issue by testarmy** [epforgpl/_mojePanstwo-Portal#466]
- Kategoria: Techniczny
- Powtarzalność: Zawsze
- Ważność: Drobny
- Priorytet: Normal
- Platforma, system, wersja: Chrome 42.0.2311.90, Windows 7
- Opis: Po wpisaniu danych adresata w polu "Adresat" i przejściu na button "Stwórz pismo" za pomocą przycisku  "TAB", dane adresata sa usuwane,
- Kroki do powtórzenia: 1. Uruchom stronę główną http://mojepanstwo.pl/ 2. Kliknij [Napisz pismo] 3. W polu "Adresat" wpisz istniejącą instytucję publiczną 4. Wciśnij "TAB" na klawiaturze aby przejśc na button "Stwórz pismo"

**Comment by Cain-Ish** [comment]
Jesli podczas wyboru ministerstwa nie zatwierdzi sie wyboru (przez wybranie go z listy) wciśnięcie TAB jest traktowane jako wyłączenie wyboru (czyli wpisane słowo jest kasowane).
Czy to jest ten błąd?
