### ISSUE TITLE
Aplikacja [Wydatki posłów] nie spełnia swojej funkcjonalności (ANDROID)

### ISSUE THREAD

**Issue by testarmy** [epforgpl/_mojePanstwo-Portal#469]
- Kategoria: Funkcjonalny
- Powtarzalność: Zawsze
- Ważność: Drobny
- Priorytet: Normal
- Platforma, system, wersja: Mobilna wersja Chrome. Android 4.4.2. LG G2 MINI 
- Opis: W aplikacji "Wydatki posłów" ucięty jest opis oraz nie ma możliwośći scrollowania.
- Kroki do powtórzenia: 1. Uruchom stronę główną http://mojepanstwo.pl/ 2. Kliknij [Wszystkie aplikacje] 3. Kliknij [Wydatki posłów] 4. Aktualny rezultat w załączniku

![id30 aplikacja wydatki poslow](https://cloud.githubusercontent.com/assets/11860622/7451979/a7db0934-f257-11e4-9a8b-5a9587032c27.png)

**Comment by danielmacyszyn** [comment]
@Cain-Ish Może na mobile wyświetlać komunikat, że apka działa tylko od jakiejś określonej rozdzielczości?
