### ISSUE TITLE
Martwy link - "Prezydent.pl"

### ISSUE THREAD

**Issue by testarmy** [epforgpl/_mojePanstwo-Portal#473]
- Kategoria: Techniczny
- Powtarzalność: Zawsze
- Ważność: Drobny
- Priorytet: Normal
- Platforma, system, wersja: Chrome 42.0.2311.90, Windows 7
- Opis: W katalogu [Media] po kliknięciu na "Prezydent.pl" w najczęściej retweetowanych treściach pojawia się błąd 404. 
- Kroki do powtórzenia: 1. Uruchom stronę główną http://mojepanstwo.pl/ 2. Kliknij [Media] 3. W dziale "Politycy" znajdź "Prezydent.pl" 4. Kliknij na link 5. Aktualny rezultat: błąd 404.

**Comment by McCease** [comment]
Link obecnie działa.
