### ISSUE TITLE
Zamówienia publiczne: link do wykonawcy

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-Portal#483]
> Czy moglibyśmy w API z zamówień publicznych dodać coś takiego? 
 zamowienia_publiczne.wykonawca_1: {id: 123456, krs: 123456, nazwa: "nazwa"}, zamowienia_publiczne.wykonawca_2: {id: 223456, krs: 223456, nazwa: "nazwa2"}

> Ponieważ łączymy podmioty przez zamówienia z KRSami i w zleceniodawcach macie podany KRS, a przy wykonawcach nie. Jeżeli macie KRSy wykonawców to byłoby świetnie, gdybyście je dodali w API.

**Comment by lzyla** [comment]
I jak? macie jakieś informacje, czy jesteście to w stanie uruchomić?

**Comment by danielmacyszyn** [comment]
Tak. Wprowadzimy te dane do API w środę do końca dnia.

**Comment by danielmacyszyn** [comment]
A więc tak:
Do obsługi danych o zamówieniach publicznych służą dwa datasety:
zamowienia_publiczne
zamowienia_publiczne_dokumenty

Jedno zamówienia publiczne (element z datasetu zamowienia_publiczne) składa się z conajmniej jednego dokumentu. Niektóre dokumenty oznaczają samo ogłoszenie zamówienia (na tym etapie nie ma jeszcze żadnych wykonawców), inne oznaczają zmianę warunków zamówienia (na tym etapie też nie ma żadnych wykonawców) a inne dokumenty oznaczają rozstrzygnięcie zamówienia - i dopiero na tym etapie pojawia się informacja o wykonawcach. Każdy element z datasetu zamowienia_publiczne_dokumenty zawiera pole parent_id, które linkuje do elementu z datasetu zamowienia_publiczne.

Elementy z datasetu zamowienia_publiczne_dokumenty zawierają pole typ_id, które oznacza typ dokumentu. Pełen słownik dla pola typ_id jest następujący:
1 - Ogłoszenie o zamówieniu
2  - Uproszczone ogłoszenie o zamówieniu
3  - Ogłoszenie o udzieleniu zamówienia (tutaj mamy wykonawców!)
6  - Ogłoszenie o zmianie ogłoszenia
7  - Ogłoszenie o zamiarze zawarcia umowy

Czyli informacja o wykonawcach jest dostępna tylko dla elementów z datasetu zamowienia_publiczne_dokumenty, dla którego typ_id=3

Takie dane można pobierać pod następującym requestem:
https://api-v2-test.mojepanstwo.pl/dane/zamowienia_publiczne_dokumenty/index?conditions[zamowienia_publiczne_dokumenty.typ_id]=3

Dane, które są zwracane zawierają pole 'static', a w nim, dane które Was interesują. Nie można szukać, ani sortować danych, po elementach pojawiających się w polu 'static'. Można je tylko przeglądać, przy okazji szukania, filtrowania i sortowania elementów z datasetu zamowienia_publiczne_dokumenty.
