### ISSUE TITLE
Proszę o aktualizację danych

### ISSUE THREAD

**Issue by dodilevante** [epforgpl/_mojePanstwo-Portal#493]
Proszę o korektę danych - widniejące dane są nieaktualne (dot. organu nadzoru) https://mojepanstwo.pl/dane/krs_podmioty/543423,stowarzyszenie-dom-kultury-niezaleznej

**Comment by McCease** [comment]
Obecne dane są zgodne z KRS. @dodilevante Czy wszystko jest teraz aktualne?

**Comment by dodilevante** [comment]
Nie są aktualne. Zmienił się organ nadzoru, a skład widnieje stary i wychodzą
powiązania stare. Proszę usunąć z organu nadzoru Agnieszkę Jóźwiak  i zdjąc
powiązania ze Stowarzyszeniem Sztuka Dobrego Życia
 

> Dnia 10 wrzesień 2015 o 18:11 McCease <notifications@github.com> napisał(a):
> 
> 
>  Obecne dane są zgodne z KRS. @dodilevante <https://github.com/dodilevante>
> Czy wszystko jest teraz aktualne?
> 
>  —
>  Reply to this email directly or view it on GitHub
> <https://github.com/epforgpl/_mojePanstwo-Portal/issues/493#issuecomment-139296535>
> .
> 
>   
> 

 
Stowarzyszenie "Dom Kultury Niezależnej" w Łodzi
KRS 0000543423, NIP 7272794710, REGON 360774004
Darowizny na cele statutowe:
Meritum Bank 41 1300 0000 2375 2461 7000 0001
Prosimy o wspieranie nas w trakcie zakupów w wybranych e-sklepach:
https://fanimani.pl/zbieramy/stowarzyszenie-dom-kultury-niezaleznej/

Uwagi: prosimy nie zwracać uwagi na ewentualny komunikat w sprawie problemów
z dostarczeniem e-maila. Poczta dochodzi:)

**Comment by McCease** [comment]
Przepraszam, wciąż oczekujemy na aktualny odpis z KRS, będę monitorał sprawę. Na dniach na stronie powinny widnieć właściwe dane.

**Comment by McCease** [comment]
Przepraszamy, że tyle to trwało. Obecnie dane są zgodne z KRS.
