### ISSUE TITLE
Nazwa użytkownika Twittera (ID) posłów ma charakter numeryczny, jakby odwołanie do jakiś trzeciego zbioru 

### ISSUE THREAD

**Issue by ad-m** [epforgpl/_mojePanstwo-Portal#499]

**Comment by ad-m** [comment]
Np. https://mojepanstwo.pl/dane/poslowie/354,sikorski-radoslaw.json
> "poslowie.twitter_account_id":"28"

**Comment by McCease** [comment]
Jest potrzebny z racji zarządzania miejscem zajmowanym przez bazę danych.

**Comment by ad-m** [comment]
Heh? Jak chce używać API to co ja mam zrobić z numerem "28"??

Wnoszę o ponowne rozpoatrzenie sprawy przez @KrzysztofMadejski , który niegdyś - wydaje się - podzielał podczas HackNight stanowisko, że w API powinna być nazwa użytkownika

**Comment by McCease** [comment]
Sugeruję precyzjniej opisywać problemy - np. Zapytanie o posła nie zwraca jego twitter id tylko id z bazy.

A co można zrobić z tym numerem? Np. pobrać informacje o koncie twitterowym: https://mojepanstwo.pl/dane/twitter_accounts/28.json
