### ISSUE TITLE
Logowanie z forum nie działa

### ISSUE THREAD

**Issue by JppPL** [epforgpl/_mojePanstwo-Portal#500]
Logowanie z forum kodujdlapolski nie działa u mnie prawidlowo

Wyrzuca nowe okno łączy się, chyba autoryzuje, i zostawia je otwarte z adresem: https://forum.kodujdlapolski.pl/auth/epanstwo/callback?state=d9b0afc2b0fd30747d67dcf52912ebffdd48466ed28c43fe&code=5a6cd3e61a00d50faa355cfc7b58cd9c0c48ff49

Testowane na Chrome i Firefox.
A bym coś napisał na forum

**Comment by KrzysztofMadejski** [comment]
@JppPL masz jeszcze ten problem? U mnie to działa ok.

Jaki masz login na forum? Jaki adres masz w przeglądarce podczas logowania do Mojego Państwa?

**Comment by JppPL** [comment]
Już działa. Może chwilowa zawieszka/ problem z połączeniem. Do zamknięcia.
