### ISSUE TITLE
Chaos w wyglądzie pisma na przejrzystykrakow.pl

### ISSUE THREAD

**Issue by ad-m** [epforgpl/_mojePanstwo-Portal#503]
Znalazłem się na przejrzystykrakow.pl, wybrałem "Napisz pismo", następnie "Odmowa wykazania…". Znalazłem się pod adresem https://przejrzystykrakow.pl/pisma/cg2S3,Odmowa-wykazania-szczegolnej-istotnosci-interesu-publicznego-w-uzyskaniu-informacji-przetworzonej/edit i dotknął mnie chaos:
![odmowa_wykazania_szczegolnej_istotnosci_interesu_publicznego_w_uzyskaniu_informacji_przetworzonej_-_2015-07-19_00 33 34](https://cloud.githubusercontent.com/assets/3618479/8763770/e947554e-2dad-11e5-8dea-46dcd956d67c.png)

Jest kilka wpisów w dev konsoli:
![zaznaczenie_344](https://cloud.githubusercontent.com/assets/3618479/8763779/65c39aec-2dae-11e5-92ea-94a0ed61a755.png)

**Comment by Cain-Ish** [comment]
Witam @ad-m,
Chciałbym dowiedzieć się kilku dodatkowych informacji:
1) czy problem istnieje dalej
2) na jakiej przeglądarce (plus wersji)
3) jaki system operacyjny

**Comment by ad-m** [comment]
1/ Problem ustał.
