### ISSUE TITLE
Swagger odpytuje kosmos 

### ISSUE THREAD

**Issue by ad-m** [epforgpl/_mojePanstwo-Portal#504]
Wybrałem https://przejrzystykrakow.pl/ , następnie w stopce API. Trafiłem na https://mojepanstwo.pl/api . Strona próbuje pobrać treści z http://api-server.dev/swagger.json . Moja, całkiem porządna przeglądarka nie dopuszcza takich żądań. Swagger się nie wyświetla.

> Mixed Content: The page at 'https://mojepanstwo.pl/api' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api-server.dev/swagger.json'. This request has been blocked; the content must be served over HTTPS.

**Comment by rjeczalik** [comment]
FYI api spec rzuca 404:

```
$ curl -i https://api-v2.mojepanstwo.pl/swagger.json
HTTP/1.1 404 Not Found
Date: Sun, 26 Jul 2015 13:45:39 GMT
Server: Apache/2.2.22 (Ubuntu)
X-Powered-By: PHP/5.3.10-1ubuntu3.18
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Content-Length: 43
Content-Type: application/json; charset=UTF-8

{"name":"Not Found","url":"\/swagger.json"}
```
