### ISSUE TITLE
Fałszowanie dat uchwał dzielnicy Krakowa

### ISSUE THREAD

**Issue by ad-m** [epforgpl/_mojePanstwo-Portal#506]
Dla https://przejrzystykrakow.pl/dzielnice/22/rada_uchwaly/15687 system wyświetla datę podjęcia:
> 18 marca 2104 r. 

Ja w to nie wierzę. To chen w przyszłości. Albo jakiś błąd, albo technologia nie z tej ziemi.

**Comment by danielmacyszyn** [comment]
Niestety takie dane są w samym źródle
http://www.bip.krakow.pl/?dok_id=57723

Spróbujemy na to znaleźć jakiś sposób walidacji...

**Comment by ad-m** [comment]
Wstawiłem się w tej sprawie do władz, aby Cię chronić.
> Temat: Skarga na Prezydenta Miasta Krakowa
> Od: naczelnik@jawnosc.tk <naczelnik@jawnosc.tk>
> Data: 20 lipca 2015 12:03
> Do: umk@um.krakow.pl, Fundacja Stańczyka <stanczyk@stanczyk.org.pl>, biuro@epf.org.pl
> Na podstawie art. 63 Konstytucji RP wnoszę skargę na działalność Prezydenta Miasta Krakowa.
> 
> Zgłaszam, że na stronie http://www.bip.krakow.pl/?dok_id=57723 wskazano, że podjęto aż dwie uchwały w 2104 roku tj.
> XLVIII  18-03-2104       611/XLVIII/2014 korekty uchwały 597/XLVII/2014 w sprawie wskazania miejsc wymagających oświetlenia i doświetlenia na terenie Dzielnicy IV
> 
> LIII 08-07-2104 683/LIII/2014 listy rankingowej zadań powierzonych w 2015 r. z zakresu prac, modernizacji, prac remontowych osiedlowej i szkolnej infrastruktury sportowej i rekreacyjnej
> To jest postępowanie niegodne, aby tak pisać w Biuletynie Informacji Publicznej. Ja w to uwierzyć nie potrafię. Ewentualnie proszę o przesłanie faktur na wehikuł czasu, skoro rada miasta jest w stanie podejmować uchwały w przyszłości.
> 
> Dodatkowo okolicznością, która podnosi znaczenie tej sprawy jest to, że wskazana usterka utrudnia funkcjonowanie Panu Danielowi Macyszynowi, który wraz z Fundacją ePaństwo chciałby z wykorzystaniem tych informacji zmienić świat na super ( https://github.com/epforgpl/_mojePanstwo-Portal/issues/506 ).
> 
> Mając na względzie powyższe wnoszę o ustalenie osób odpowiedzialnych za wskazane naruszenia, usunięcie przedstawionych naruszeń, a przede wszystkim doprowadzenie, aby takie sytuacje nie miały miejsca w przyszłości.
> 
> Z wyrazami szacunku,

**Comment by ad-m** [comment]
Ok, Kraków naprawił dane. Teraz Warszawa.

**Comment by ad-m** [comment]
Naprawione. 

W dalszym ciągu oczekuje na załatwienie skargi przez Radę Miasta Krakowa. 16 października br. napisałem donos do Wojewody.
