### ISSUE TITLE
Dane nadawcy nie powinny być wymangane przy wniosku

### ISSUE THREAD

**Issue by ad-m** [epforgpl/_mojePanstwo-Portal#509]
Stanowczo protestuje wobec wymagania innych niż przewidziane przez prawo informacji w wniosku o informacje publiczną. Nie mogę zapisać formularza wniosku o informacje publiczną podczas pisania wniosku do ePF (por. #508), bo wymaga się ode mnie moich danych osobowych. Tak być nie powinno. 
![zaznaczenie_347](https://cloud.githubusercontent.com/assets/3618479/8763866/915458be-2db2-11e5-8a09-4e2888b792f8.png)

Ja stanowczo protesuje. Ja nie chce tych danych podawać. Prawo mnie do tego nie obliguje to dlaczego Wy :confused:

**Comment by ad-m** [comment]
Za prawidłowy wniosek pisemny uznaje się również przesłanie zapytania pocztą elektroniczną i to nawet gdy do jej autoryzacji nie zostanie użyty podpis elektroniczny (Wyrok NSA z dnia 14 września 2012 roku w sprawie sygn. akt. I OSK 1013/12; Wyrok NSA z dnia 16 marca 2009 roku w sprawie sygn. akt. I OSK 1277/08, Wyrok NSA z dnia 30 listopada 2012 roku w sprawie sygn. akt. I OSK 1991/12), ani nie zostanie wyraźnie zawarta podstawa prawna (Wyrok WSA w Krakowie z dnia 07 kwietnia 2014 roku w sprawie sygn. akt. II SAB/Kr 13/14).

Nie dopuszczalne jest wymaganie skorzystania z określonego formularza(Wyrok WSA w Warszawie: II SAB/Wa 57/09 ), w szczególności, ale nie wyłącznie wymagającego podania danych innych niż niezbędne do udostępnienia informacji (GIODO o formularzu wniosku o udostępnienie informacji publicznej. Pozarządowe Centrum Dostępu do Informacji Publicznej, 2013.). Jakiekolwiek dodatkowe wymogi odnośnie formy wniosku o udostępnienie informacji publicznej nie mogą wywołać po stronie wnioskodawcy negatywnych skutków prawnych (II SAB/Wa 351/12 - Wyrok WSA w Warszawie).

**Comment by McCease** [comment]
@Karo-ePF

**Comment by ad-m** [comment]
Takie stanowisko przyjął ostatnio NSA w mojej sprawie (por. https://www.facebook.com/adam.dobrawy/posts/427924950728071 , https://www.facebook.com/photo.php?fbid=10204887955938778&set=p.10204887955938778&type=1 , I OSK 1808/14 ).

**Comment by McCease** [comment]
Rozwiazanie gotowe, czeka do wejsca na produkcje.
