### ISSUE TITLE
Jestem nikim - pominięcie użytkownika w aplikacji media

### ISSUE THREAD

**Issue by ad-m** [epforgpl/_mojePanstwo-Portal#513]
Nie znam doboru kont, ale zastanawia mnie … 
![adobrawy_-_2015-07-19_12 07 49](https://cloud.githubusercontent.com/assets/3618479/8765508/ce1b0e8a-2e0e-11e5-9c86-a34f429ad4a6.png)
https://mojepanstwo.pl/media/twitter_konta?q=adobrawy

**Comment by danielmacyszyn** [comment]
@ad-m 
Do obserwowanych kont dodajemy konta polityków, NGO, instytucji publicznych i komentarów politycznych, z największą liczbą followersów. Chcesz, żeby dodać Twoje konto do listy obserwowanych?

**Comment by ad-m** [comment]
Tak.

BTW. Warto zamieścić kogo dodajecie po prostu na stronie.

Wysłano z urządzenia mobilnego.
20 lip 2015 9:56 AM "danielmacyszyn" <notifications@github.com> napisał(a):

**Comment by MarekBielecki** [comment]
Od teraz na https://mojepanstwo.pl/media każdy ma możliwość zgłaszania swojego konta do listy obserwowanych.
