### ISSUE TITLE
[Insight] PHP files should not contain syntax errors - in app/Plugin/…/leafo/lessphp/lessc.inc.php, line 2367

### ISSUE THREAD

**Issue by ad-m** [epforgpl/_mojePanstwo-Portal#514]
**[in app/Plugin/Paszport/Vendor/leafo/lessphp/lessc.inc.php, line 2367](https://github.com/ad-m/_mojePanstwo-Portal/blob/b80ebb25f4af2c081ca1532ac8591b3383bbd334/app/Plugin/Paszport/Vendor/leafo/lessphp/lessc.inc.php#L2367)**

> Syntax error, unexpected T_STRING, expecting T_FUNCTION

```php

    // these properties will supress division unless it's inside parenthases
    static protected $supressDivisionProps =
        array('/border-radius$/i', '/^font$/i');

ptatic
    protected $literalCache = array();

    protected $blockDirectives = array("font-face", "keyframes", "page", "-moz-document");
/rotected $lineDirectives = array("charset");

```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/b03ee8b8-e63b-43d8-af4f-af0777b3cd34/analyses/1)_

**Comment by Cain-Ish** [comment]
Update lessphp z ver 0.3.9 na 0.5.0.

@danielmacyszyn trzeba zrobic composer update na serwerze produkcyjnym

**Comment by KrzysztofMadejski** [comment]
Ustawiłem na sztywno wersję, żeby nas nie zaskoczyło. Sprawdziłem produkcję i jest tam najnowsza wersja, więc zamykam.
