### ISSUE TITLE
[Insight] PHP debug statements found - in app/Plugin/…/leafo/lessphp/lessify.inc.php, line 437

### ISSUE THREAD

**Issue by ad-m** [epforgpl/_mojePanstwo-Portal#515]
**[in app/Plugin/Paszport/Vendor/leafo/lessphp/lessify.inc.php, line 437](https://github.com/ad-m/_mojePanstwo-Portal/blob/b80ebb25f4af2c081ca1532ac8591b3383bbd334/app/Plugin/Paszport/Vendor/leafo/lessphp/lessify.inc.php#L437)**

> `print_r()` should only be used for debug, and not committed to the source code repository.

```php
 */
class lessify extends lessc
{
    public function dump()
    {
        print_r($this->env);
    }

    public function parse($str = null)
    {
        $this->prepareParser($str ? $str : $this->buffer);
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/b03ee8b8-e63b-43d8-af4f-af0777b3cd34/analyses/1?status=violations)_

**Comment by Cain-Ish** [comment]
Update lessphp z ver 0.3.9 na 0.5.0.

@danielmacyszyn trzeba zrobic composer update na serwerze produkcyjnym

**Comment by danielmacyszyn** [comment]
Zrobione
