### ISSUE TITLE
Autoryzacja aplikacji

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-Portal#521]
- [x] Nowy tab na profilu użytkownika "Aplikacje API"
- [x] Na nim lista aplikacji (nazwa + edytuj)
- [x] Tworzenie / Wyświetlanie / Edycja aplikacji
  - [ ] Pola: Nazwa / logo / Strona domowa / opis / typ / Link do polityki prywatności / Link do regulaminu serwisu 
  - [x] Typ: Aplikacja webowa lun Aplikacja serwerowa (po utworzeniu nie można zmienić)
  - [x] Pole: klucz API - pole wyświetlane dla utworzonej aplikacji, w postaci zagwiazdkowanej; przycisk `Pokaż`, przycisk `Zresetuj klucz` (prompt do potwierdzenia)
  - [x] Pole: domena - pole dla aplikacji webowej
  - [x] `Usuń aplikację` (prompt do potwierdzenia)

- [x] Podobna lista wyświetlana adminowi

**Comment by KrzysztofMadejski** [comment]
Wersja 2.0 to jest administracja poszczególnymi uprawnieniami (np. prawo do odczytywania notyfikacji użytkownika).

Aktorzy:
- twórca aplikacji (prosi administratora serwisu o nadanie konkretnych ról)
- administrator serwisu (ogląda zapytania o nadanie ról twórców aplikacji, akceptuje lub odrzuca z podaniem przyczyny)
- użytkownik (wyraża zgodę, aby dana aplikacja mogła wykonywać konkretne akcje w jego imieniu)

Rola:
- nazwa
- krótki opis

Widok dla twórcy aplikacji (per aplikacja):
- Lista wszystkich ról, może prosić o autoryzację lub zrezygnować z danej roli 
  - Rola: nazwa, opis, status (włączona / wyłączona / oczekuje na autoryzację)
    - ? Status: zielony / szary / pomarańcz, przycisk 
![mp-api-button](https://cloud.githubusercontent.com/assets/849975/8926806/0241252c-3513-11e5-9e29-adcc8f327a51.PNG) + tekst?

Widok dla administratora:
- Lista wszystkich aplikacji; wszystkich użytkowników; możliwość podglądu danych aplikacji; zarządzanie jej uprawnieniami; podświetlone aplikacje, których twórcy proszą o uprawnienia

Widok dla użytkownika:
- Coś ala FB lub Google (to co z prawej na poniższym obrazku)
![api-acl-consent-screen](https://cloud.githubusercontent.com/assets/849975/8926885/9c9a19bc-3513-11e5-8adf-0648fa477855.PNG)

**Comment by ArekSoldon** [comment]
![dodajapp](https://cloud.githubusercontent.com/assets/3994690/8927342/0b8faee2-3517-11e5-92f0-47f49a7f229c.png)
![applist](https://cloud.githubusercontent.com/assets/3994690/8927341/0b8b0310-3517-11e5-9bde-b5c47cd2f732.png)

**Comment by KrzysztofMadejski** [comment]
@danielmacyszyn do przegadania jak będziesz miał chwilę

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish prośba o ostylowanie tego. :)

Pozostaje jeszcze kwestia poradzenia sobie z logiem..

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish poprawiłem trochę fronteend, ale widzę że sporo się zmieniło od tego czasu.

Potrzebuję żebyś przeniósł http://mojepanstwo.dev/paszport/api_apps
do wyglądu, który obowiązuje na http://mojepanstwo.dev/konto

Jak coś na backendzie też trzeba przenieść to daj znać.

**Comment by KrzysztofMadejski** [comment]
Przy okazji @danielmacyszyn i @MarekBielecki zwracam uwagę na:

1. https://github.com/epforgpl/_mojePanstwo-Portal/blob/afe65f738641cf3715f0f3dd7734feaedc7301e9/app/Model/Datasource/mpAPISource.php#L376
2. https://github.com/epforgpl/_mojePanstwo-Portal/blob/afe65f738641cf3715f0f3dd7734feaedc7301e9/app/Model/Datasource/mpAPISource.php#L313
