### ISSUE TITLE
Aktualizacja zmiana adresu 

### ISSUE THREAD

**Issue by Emilia124** [epforgpl/_mojePanstwo-Portal#525]
Firma LeasePlan zmieniła siedzibę. Obecny adres to:

ul. Postępu 14B
02-676 Warszawa
Pełne dane kontaktowe: http://leaseplan.pl/pu/pl/KONTAKT;jsessionid=DCDEA93D181DF163C99551087DE499D8.node4 

Serdecznie proszę o aktualizację. Wizytówka fimy na państwa portalu zanjduje sie pod adresem: 
https://mojepanstwo.pl/dane/krs_podmioty/93257,leaseplan-fleet-management-polska

**Comment by ad-m** [comment]
Dziękuje za informacje.

**Comment by danielmacyszyn** [comment]
Poprawione
