### ISSUE TITLE
Nie działający link - 500

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-Portal#526]
https://mojepanstwo.pl/sejmometr/sejmometr

po kliknięciu na pierwszą pozycję (Posłowie) w menu górnym na https://mojepanstwo.pl/sejmometr/poslowie?

**Comment by ad-m** [comment]
Z ciekawości, bo obserwuje jakiś czas repo, a nie znalazłem na to dowodów.
Błędy 500 logujecie w jakiś sposób po stronie aplikacji, aby je przekazać
do naprawy?

Wysłano z urządzenia mobilnego.
28 lip 2015 21:07 "Krzysiek Madejski" <notifications@github.com> napisał(a):

**Comment by KrzysztofMadejski** [comment]
Nie

**Comment by ad-m** [comment]
Polecam sentry. Widzę, że są rozwiązania do CakePHP, choć nie znam ich.

Ja u klientów używam przy Django. Bardzo komfortowo dostać pełen stacktrace
z wgladem zmienne lokalne. Dostać to do aplikacji, która wspólne źródło
połączy w jedną usterkę i pozwoli analizować zgłoszenia u wspólnym punkcie
wspólnym razem. Do tego statystyki kiedy 500 najczęściej, jakie
przeglądarki w danej usterce najczęściej, ilość błędów na przestrzeni czasu.

Inne, ale płatne i bardziej zaawansowane to Appenlight i NewRelic.

W Django wdrożenie Sentry to kilka linijek do skopiowania z dokumentacji.
NewRelic to zupełnie bajka - edytujesz tylko Procfile.

Wysłano z urządzenia mobilnego.
28 lip 2015 22:18 "Krzysiek Madejski" <notifications@github.com> napisał(a):

**Comment by KrzysztofMadejski** [comment]
Dzięki, a może byś miał chwilę nam postawić to rozwiązanie na którymś hacknight?

**Comment by ad-m** [comment]
Serwer Sentry - nie ma problemu. Wystarczy mi jakieś konto SSH (bez roota)
i baza.

Dla CKANa mogę pomyśleć. Dla CakePHP...Nie każ mnie tak...;-)

Wysłano z urządzenia mobilnego.
28 lip 2015 22:35 "Krzysiek Madejski" <notifications@github.com> napisał(a):

**Comment by ad-m** [comment]
Jeszcze redis byłby wskazany, ale może działać z poziomu użytkownika.

Wysłano z urządzenia mobilnego.
28 lip 2015 10:40 PM <naczelnik@jawnosc.tk> napisał(a):

**Comment by McCease** [comment]
Nieaktualne.
