### ISSUE TITLE
NGO: Nie mogę ustawić zdjęcia działań

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-Portal#529]
- na Chrome nie pojawia się nawet ono po wybrniu
- w Firefox pojawia się po wybraniu, ale po kliknięciu Zapisz, nie jest zapamiętywane

**Comment by AsiaPrzybylska** [comment]
Dodawanie zdjęć zostało kilkakrotnie przetestowane. Wszystko powinno działać poprawnie.
