### ISSUE TITLE
Własna petycja do posłów

### ISSUE THREAD

**Issue by ad-m** [epforgpl/_mojePanstwo-Portal#530]
Szanowni,

Zarabiam na wolnym i otwartym oprogramowaniu ( https://github.com/watchdogpolska/prezydent.siecobywatelska.pl), w sumie też trochę lobbing tj. zlecono mi wykonanie narzędzia do petycji. Kod na https://github.com/ad-m/petycja-faoo . Petycja niepublikowana.

Czy i na jakich zasadach można dodać petycje o słusznych celach i wartościach do narzędzia petycji? Klient sobie życzy, aby było jak na naszrzecznikl.pl. :+1:

Jestem przekonany, że tego rodzaju petycja będzie odpowiadać realizacjom celom Fundacji ujętym w hasłach na epf.org.pl, w szczególności ```Dajemy obywatelom wiedzę i narzędzia do ulepszania swojego państwa.```

Dacie się wykorzystać? 

Z poważaniem,

**Comment by danielmacyszyn** [comment]
Czy chodzi Ci o to, żeby dodać funkcjonalność petycji do Twojego czy naszego (mojepanstwo) softu?

**Comment by ad-m** [comment]
Dodać petycję z moją treścią, tak jak dkdank naszrzecznik.

Wysłano z urządzenia mobilnego.
31 lip 2015 8:33 AM "danielmacyszyn" <notifications@github.com> napisał(a):

**Comment by ad-m** [comment]
Już nieaktualne.
