### ISSUE TITLE
Dyskryminacja partii politycznych pod względem Twitterów

### ISSUE THREAD

**Issue by ad-m** [epforgpl/_mojePanstwo-Portal#532]
Na https://mojepanstwo.pl/media/twitter_konta?&conditions[twitter_accounts.typ_id]=8 jest tylko PO.

Tymczasem:
* http://twitter.com/pisorgpl
* https://twitter.com/partia_korwin
* https://twitter.com/sldpoland 

Ogólnie interesującym źródłem danych wydaje się http://www.sotrender.pl/trends/twitter/reports/201506/politycy .

**Comment by McCease** [comment]
Lista partii uzupełniona, w przeciągu kilku najbliższych dni zostaną zebrane ich tweety.
