### ISSUE TITLE
Pominięcie Ministerstwa Środowiska z Twitterów

### ISSUE THREAD

**Issue by ad-m** [epforgpl/_mojePanstwo-Portal#533]
https://twitter.com/minsrod

Mam wrażenie, że i tak kilka ministerstw uciekło.

**Comment by ad-m** [comment]
Inne urzędy można próbować odszukać przez https://twitter.com/Karkonosz/lists/politycy-i-urz%C4%99dy/members .

**Comment by MarekBielecki** [comment]
Od teraz na https://mojepanstwo.pl/media każdy ma możliwość zgłaszania swojego konta do listy obserwowanych.

**Comment by ad-m** [comment]
To nie jest mój profil. 

Mam napisać do Ministerstwo Środowisko w tej sprawie, czy sfałszować formularz?

![zaznaczenie_439](https://cloud.githubusercontent.com/assets/3618479/9701633/041a36ba-5433-11e5-8e6d-87ae2aace869.png)
![zaznaczenie_440](https://cloud.githubusercontent.com/assets/3618479/9701634/068de54a-5433-11e5-9ec2-6817789006cd.png)
