### ISSUE TITLE
Zmienić nazwę usera na Uzytkownik Mojego Państwa i zmienić logo

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-Portal#535]
https://github.com/UzytkownikSejmometru

I sprawdzić, czy działa zgłaszania issues via formularz

**Comment by ad-m** [comment]
Znacie gitreports.com? Jest już przetłumaczone (por. schneidmaster/gitreports.com#79) i nie musicie utrzymywać. 

W Poradni feedback zdecydowałem jednak zbierać w panelu administracyjnym aplikacji (watchdogpolska/poradnia#129) ze względu na możliwość umieszczenia danych prywatnych, ale umożliwiam jednym przyciskiem przeniesienie na GitHub. Na podobnej zasadzie (issues opt-in) Sentry integruje się z GitHubem.

**Comment by Cain-Ish** [comment]
Zmieniono nazwe konta na https://github.com/uzytkownikmojegopanstwa , usunięto go tez z Bug Report Team jako że anonimowa opcja zgłaszania błędów jest tymczasowo wyłączona.
Rzuce w wolnej chwili okiem an gitreports.com

**Comment by KrzysztofMadejski** [comment]
Gitreports to nie dla nas. Jak będziemy chcieć mieć anonimowe zgłaszanie to
lepiej to robić przez formulaz na stronie MP. Przekierowanie na zewnętrzną
stronę będzie dla użytkowników "konfundujące".

2015-08-10 16:18 GMT+02:00 Cain <notifications@github.com>:

> Zmieniono nazwe konta na https://github.com/uzytkownikmojegopanstwa ,
> usunięto go tez z Bug Report Team jako że anonimowa opcja zgłaszania błędów
> jest tymczasowo wyłączona.
> Rzuce w wolnej chwili okiem an gitreports.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/epforgpl/_mojePanstwo-Portal/issues/535#issuecomment-129470169>
> .
>



-- 
Krzysztof Madejski
Koordynator Koduj Dla Polski, Fundacja ePaństwo
Code for Poland program manager, ePF Foundation
http://epf.org.pl
http://kodujdlapolski.pl
krzysztof.madejski@epf.org.pl
+48 664 082 823

**Comment by ad-m** [comment]
Przy okazji tego zgłoszenia warto mieć na uwadze #183
