### ISSUE TITLE
VaGla jest także politykiem

### ISSUE THREAD

**Issue by ad-m** [epforgpl/_mojePanstwo-Portal#543]
https://mojepanstwo.pl/dane/twitter_accounts/152

Senator

**Comment by ad-m** [comment]
Przy okazji…Jakie wpisy są udostępniane na stronie? Nie ma wszystkich senatora.

**Comment by McCease** [comment]
VaGla nie jest senatorem, dopiero zgłosił chęć kandydowania w najbliższych wyborach i zbiera podpisy.

**Comment by ad-m** [comment]
Kim jest polityk?

**Comment by McCease** [comment]
Za SJP PWN: Polityk - osoba zawodowo zajmująca sie polityką.

**Comment by McCease** [comment]
Jego status zostanie zmieniony, jeżeli obejmie urząd senatora.
