### ISSUE TITLE
[Propozycja] Zgłaszanie kont social media do portalu

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-Portal#547]
Fajnie jakby na https://mojepanstwo.pl/media był banerek pozwalający na zgłaszanie dodatkowych kont. W crowdsource siła!

**Comment by ad-m** [comment]
:clap:

**Comment by danielmacyszyn** [comment]
@ArekSoldon Daj jakiś baner, żeby umieścić w lewej kolumnie na https://mojepanstwo.pl/media
Proponowany tekst: Chcesz abyśmy analizowali również Twoją aktywność? Dodaj swoje konto >>

@MarekBielecki Zrób modala z dodawaniem nazwy konta i zapisywaniem do bazy

**Comment by McCease** [comment]
Planujemy monitorować co ludzie dodają? Żebyśmy nie hostowali jakiś dziwnych tweetów, od randomowych ludzi.

**Comment by KrzysztofMadejski** [comment]
Oczywiście. Musimy mieć wewnętrzną moderację zgłoszeń.

2015-08-24 10:09 GMT+02:00 McCease <notifications@github.com>:

> Planujemy monitorować co ludzie dodają? Żebyśmy nie hostowali jakiś
> dziwnych tweetów, od randomowych ludzi.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/epforgpl/_mojePanstwo-Portal/issues/547#issuecomment-134085170>
> .
>



-- 
*Krzysztof Madejski*
<karolina.wysocka@epf.org.pl>Code for Poland Program Manager / Koordynator
Koduj Dla Polski
krzysztof.madejski@epf.org.pl / +48 664 082 823

* <http://www.epf.org.pl/>*

**Comment by ArekSoldon** [comment]
![screen-shot-2015-08-24-at-20 27 16](https://cloud.githubusercontent.com/assets/3994690/9448928/ba833778-4a9f-11e5-85e2-bd8ede3d1eac.jpg)

**Comment by ad-m** [comment]
@KrzysztofMadejski , ja proponuje zrobić moderacje opartą na czarnej liście użytkowników / kont, czyli wszystkie zmiany widoczne od razu, a możecie kasować i blokować. Na Wikipedii to działa. Z mojej perspektywy nie muszę czekać na jakieś zatwierdzenie i mogę napisać gdzieś, że dzięki mnie przybyło danyc lub się skrzyknąć w kilka osób. 

Poza tym przy modelu opt-out będziecie mieć z tym systemie mniej pracy, a na brak pracy raczej nie narzekacie.
Skandaliczne treści sam Twitter kasuje już dziś…
@ArekSoldon , dotąd na ePF raczej gradientu nie stosowano. Jesteś pewien, że chcesz go tu wprowadzić?

**Comment by orian** [comment]
Jaki jest status tego zgłoszenia?

Mam kilka kont lokalnych polityków: https://twitter.com/grzymowicz albo https://twitter.com/kacprzycki które z naszej lokalnej perspektywy byłyby warte monitorowania.
