### ISSUE TITLE
[Błąd] Nie działa wyszukiwarka gmin w finansach gmin

### ISSUE THREAD

**Issue by annadobrowolska** [epforgpl/_mojePanstwo-Portal#548]
Nie można wyszukać danych o finansach danej gminy.

Kroki reprodukcji:
- wejść na https://mojepanstwo.pl/finanse_gmin
- zacząć wpisywać w wyszukiwarce gmin np. Lublin
- z pokazującej się listy rozwijanej wybrać Lublin
- zamiast szukanych informacji jest zatrzymane kółko oznaczające oczekiwanie

Występuje na Google Chrome (wersja 44.0.2403.155)

**Comment by ad-m** [comment]
Potwierdzam i ubolewam.Fx 42.0a2 (2015-08-15), Ubuntu.

W dniu 17 sierpnia 2015 22:52 użytkownik annadobrowolska <
notifications@github.com> napisał:
