### ISSUE TITLE
Obserwuj

### ISSUE THREAD

**Issue by kmikolajczyk** [epforgpl/_mojePanstwo-Portal#549]
Dowolna gmina. Np. Warszawa https://mojepanstwo.pl/dane/gminy/2226,warszawa
Kiedy chce ja obserwowac (otwiera sie nowe okno z mozliwoscia wybrania co chce obserwowac - przy czym nie moge "odkliknac" poszczegolnych pozycji). Po kliknieciu "zapisz" link zmienia sie na
https://mojepanstwo.pl/dane/gminy/2226,warszawa# , nic sie nie dzieje i nic nie pojawia sie w obserwowanych

**Comment by Cain-Ish** [comment]
Błąd poprawioną wraz ze zmianą silnika + layout
