### ISSUE TITLE
Sprzawdzić czy wszystkie wystawiane dane dla DataBrowser są potrzebne

### ISSUE THREAD

**Issue by Cain-Ish** [epforgpl/_mojePanstwo-Portal#553]
http://mojepanstwo.local/bdl?dataset[]=bdl_wskazniki&q=test

: Undefined index: label [APP\Plugin\Dane\View\Elements\DataBrowser\browser-content-filters.ctp, line 19]" data-is-selected="" data-selected="">

**Comment by danielmacyszyn** [comment]
Poprawione
