### ISSUE TITLE
Brak możliwości wysłania pisma jeśli wysłało się jakieś

### ISSUE THREAD

**Issue by kmikolajczyk** [epforgpl/_mojePanstwo-Portal#554]
Po zalogowaniu i wysłaniu pisma; znika możliwość wysłania kolejnego.
W panelu po lewej stronie mam "pisma" i brak możliwości wygenerowania nowego
![screen shot 2015-08-25 at 14 01 29](https://cloud.githubusercontent.com/assets/13255614/9466032/e7941a2e-4b31-11e5-9608-ee025168a71f.png)

**Comment by kmikolajczyk** [comment]
Jesli usune pismo, moge wysłać nowe pismo. 
Ale wtedy trace całą historie pism...

**Comment by danielmacyszyn** [comment]
Przywrócono menu pozwalające na nawigację w pismach
