### ISSUE TITLE
Zgłaszanie Twitterów nie gra z wykresami

### ISSUE THREAD

**Issue by ad-m** [epforgpl/_mojePanstwo-Portal#560]
1. Wchodzimy na https://mojepanstwo.pl/media?a=9 
2. Zjeżdzamy na dół strony.
3. Wybieramy "Dodaj konto"
4. O_o ![media - polityka w mediach spolecznosciowych - chromium_437](https://cloud.githubusercontent.com/assets/3618479/9701626/723bd686-5432-11e5-8cad-7eac63fb9aca.png)
Wersja 44.0.2403.89 Ubuntu 14.04

**Comment by McCease** [comment]
Poprawione, czeka na pull.
