### ISSUE TITLE
Media: Brak ikonki Facebooka

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-Portal#562]
https://mojepanstwo.pl/media/img/twitterapp/facebook.png 

![bug_facebook_icon](https://cloud.githubusercontent.com/assets/849975/9741803/ba116cb0-565c-11e5-8b0c-bdab73fb0c27.PNG)

**Comment by AsiaPrzybylska** [comment]
Sprawdzałam na kilku stronach, powinno wyświetlać się już poprawnie.
