### ISSUE TITLE
"Przeglądaj statystyki GUS zebrane w  BLD" przykłady zwacaja te saME

### ISSUE THREAD

**Issue by lzdziana** [epforgpl/_mojePanstwo-Portal#563]
Podane tu https://mojepanstwo.pl/api/bdl przykłady zwracają identyczne dane:

https://api-v3.mojepanstwo.pl/bdl/series?metric_id=762
https://api-v3.mojepanstwo.pl/bdl/series?metric_id=762&slice=[5479,1713]
https://api-v3.mojepanstwo.pl/bdl/series?metric_id=762&slice=[5479,*]

???

**Comment by KrzysztofMadejski** [comment]
Pośrednio dzięki działalności rzeczniczej Fundacji, a bezpośrednio dzięki zaangażowanemu zespołowi Ministerstwa Cyfryzacji i GUS, BDL posiada już własne oficjalne API: https://api.stat.gov.pl/
Polecamy skorzystać z niego.
