### ISSUE TITLE
Uszkodzony JSON

### ISSUE THREAD

**Issue by mik-laj** [epforgpl/_mojePanstwo-Portal#578]
Dzień dobry,
Zapytanie: view-source:https://api-v3.mojepanstwo.pl/schemas/dane/zbiory.json zwraca nie poprawnie sformatowany plik json w 71 linii.

Pozdrawiam

**Comment by ad-m** [comment]
Powtórka epforgpl/_mojePanstwo-API-Server#43 , więc ```usuń konto```.
