### ISSUE TITLE
Publiczne spółki gminy w widoku tej gminy

### ISSUE THREAD

**Issue by ad-m** [epforgpl/_mojePanstwo-Portal#580]
Szanowni,

Zwracam się z zapytaniem o możliwość wymienienia na stronie gminy spółek w którym gmina ma udziały, a także odwrotnie - podlinkowanie gminy na stronie spółki w sekcji udziałów.

Przykładowo https://mojepanstwo.pl/dane/krs_podmioty/63479,zaklad-gospodarki-komunalnej miałby link do Gminy Kąty Wrocławskie ( https://mojepanstwo.pl/dane/gminy/761,katy-wroclawskie ).

Ewentualnie proszę choć o sporządzenie zestawienia numerów KRS / ID ePF podmiotów, których udziałowcem są podmioty publiczne. O szczegóły dopytam API ( https://gist.github.com/ad-m/c8e190ea820797be5d6d ).

Z wyrazami szacunku,

**Comment by danielmacyszyn** [comment]
@McCease W analizatorze, który działa na tabeli krs_wspolnicy dodaj rozpoznawanie gmina_id (potencjalnie powiat_id i wojewodztwo_id)

**Comment by MarekBielecki** [comment]
Dodałem wyświetlanie podmiotów na stronie gmin oraz dodałem linkowanie do gmin oraz powiatów na stronach podmiotów.

**Comment by ad-m** [comment]
Mogę prosić o podanie gdzie te dane się wyświetlają dla przywołanych wcześniej przykładów związanych z Kątami Wrocławskimi?

**Comment by MarekBielecki** [comment]
Zmiany będą widoczne po najbliższej aktualizacji kodu na produkcji.
