### ISSUE TITLE
Błąd na mamprawowiedziec.pl

### ISSUE THREAD

**Issue by Magdabiernat** [epforgpl/_mojePanstwo-Portal#581]
Na mamprawowiedziec.pl po wpisaniu adresu, a następnie przesortowaniu pojawiającej się poniżej listy kandydatów po dowolnym kryterium w Waszej aplikacji wyskakuje błąd 404.

**Comment by danielmacyszyn** [comment]
Zgłoszone ekpie MPW. Poprawiają...
