### ISSUE TITLE
Mapa: numery okręgów do Senatu nie po kolei

### ISSUE THREAD

**Issue by chastell** [epforgpl/_mojePanstwo-Portal#585]
https://mojepanstwo.pl/mapa/miejsce/164 – po rozwinięciu „Wybory parlamentarne 2015” okręgi do Senatu są w kolejności 43, 42, 44, która sprawia wrażenie dość dowolnej. ;)

**Comment by Cain-Ish** [comment]
Poprawka została wysłana i będzie widoczna na produkcji niedługo
