### ISSUE TITLE
brak grafów powiązań osób i podmiotów gosp.

### ISSUE THREAD

**Issue by pawelosipowski** [epforgpl/_mojePanstwo-Portal#594]
Witam, sprawdzałem na najnowszej Operze, Firefox, Chrome w Win10 i na chromium 45.0.2454.85 w Ubuntu 14.04 (virtualbox). Nie wyświetlają się animowane grafiki powiązań organizacji i osób.
Pozdrawiam,

**Comment by danielmacyszyn** [comment]
Zawiesił się serwer REDIS. Wyświetlanie graphów zostało uniezależnione od REDISa. Badamy czemu się zawiesił.
