### ISSUE TITLE
nie wyświetla się informacja o powiązaniach podmiotu

### ISSUE THREAD

**Issue by igor2901** [epforgpl/_mojePanstwo-Portal#597]
Nie wyświetlają się informacje o powiązaniach w ramach wyświetlenia szczegółowych informacji podmiotu

dodatkowo
brak możliwości ściągnięcia pliku KRS (po wybraniu przycisku "kliknij aby pobrać" nic się nie dzieje)

google chrome Wersja 46.0.2490.80 m 
taki sam objaw z przeglądarki Microsoft Edge 20.10240.x

pozdrawiam

**Comment by danielmacyszyn** [comment]
Proszę o podanie adresu strony, na której wystąpił błąd.

**Comment by igor2901** [comment]
Aktualnie sie wyświetla 
Incydent do zamknięcia

Wysłane z iPhone'a

Dnia 11.12.2015 o godz. 09:28 danielmacyszyn <notifications@github.com> napisał(a):
