### ISSUE TITLE
Brak danych w api dot. gmin

### ISSUE THREAD

**Issue by grzonu** [epforgpl/_mojePanstwo-Portal#598]
Pokazuje dane dot. powiatu Toruń
https://api-v3.mojepanstwo.pl/dane/miejsca/?conditions[miejsca.powiat_id]=326&conditions[miejsca.typ_id]=3
A w jsonie: "miejsca.gmina_id":"2141"
niestety 
https://api-v3.mojepanstwo.pl/dane/gminy/2141 zwraca 
{"name":"Not Found","url":"\/dane\/gminy\/2141"}

**Comment by danielmacyszyn** [comment]
Błąd wynikał z chwilowej awarii serwera. Staramy się, żeby to się nie powtórzyło w przyszłości.
