### ISSUE TITLE
Błędne dane dotyczące płci dzieci

### ISSUE THREAD

**Issue by zozlak** [epforgpl/_mojePanstwo-Portal#599]
Ze strony https://mojepanstwo.pl/dane/bdl_wskazniki/1116,dzieci-wg-pojedynczych-rocznikow-wieku wynika, że w rocznikach 2003-2004 w Polsce nie było ani jednego chłopca, a jedynie dziewczynki :-)

Domyślam się, że problem wynika z niedoskonałości źródła danych, lecz może w takim razie nie ma sensu pokazywać rozbicia na płeć dla roczników 2003-2004?

Analiza zyskałaby też na tym, gdyby synchronizować ze sobą skale pionowe wykresów - obecne ustawienia: 
- ogółem od 600 tys. do 1 mln, 
- chłopcy od -250 tys. (sic!) do 750 tys. 
- dziewczęta od 250 tys. do 750 tys.

dość skutecznie utrudniają porównywanie wykresów

**Comment by KrzysztofMadejski** [comment]
Pośrednio dzięki działalności rzeczniczej Fundacji, a bezpośrednio dzięki zaangażowanemu zespołowi Ministerstwa Cyfryzacji i GUS, BDL posiada już własne oficjalne API: https://api.stat.gov.pl/
Polecamy skorzystać z niego.
