### ISSUE TITLE
bledne dane na stronie czas-poszukiwania-pracy-wg-plci-miejsca-zamieszkania

### ISSUE THREAD

**Issue by kindee** [epforgpl/_mojePanstwo-Portal#602]
Dla kazdej z podkategorii dane sa identyczne, czyzby to blad?
https://mojepanstwo.pl/dane/bdl_wskazniki/41314,czas-poszukiwania-pracy-wg-plci-miejsca-zamieszkania

**Comment by danielmacyszyn** [comment]
Dane są bardzo podobne, ale nieidentyczne. Takie same jak w źródle (GUS).
