### ISSUE TITLE
Błąd przy wysyłce petycji

### ISSUE THREAD

**Issue by domagaj** [epforgpl/_mojePanstwo-Portal#605]
∫ 1 5 9 ⁢ x 2 + 4 ⁢ x + 2 ⁢ ⅆ x = ⁢ ⁢ 3 ⁢ x 3 + x 2 + 2 ⁢ x ⁢ 5 , ⁢ = ⁢ 3 5 2 + 5 2 + 2 5 - 3 1 3 + 1 2 + 2 1
500
UPS!COŚ POSZŁO NIE TAK
Wystąpił wewnętrzny błąd serwera.
Pracujemy nad rozwiązaniem sprawy.

**Comment by danielmacyszyn** [comment]
Poprawione

**Comment by domagaj** [comment]
Dziękuję :)

2015-12-11 9:32 GMT+01:00 danielmacyszyn <notifications@github.com>:

> Closed #605 <https://github.com/epforgpl/_mojePanstwo-Portal/issues/605>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/epforgpl/_mojePanstwo-Portal/issues/605#event-489104552>
> .
>



-- 
Pozdrawiam
Jacek Domagała
