### ISSUE TITLE
problem z wyświetlaniem zawartości strony - mapa

### ISSUE THREAD

**Issue by kokonmaster** [epforgpl/_mojePanstwo-Portal#608]
Witam,

Podczas przeglądania państwa strony mojepanstwo.pl natknąłem się na następujący problem: po wejściu na stronę mapy: https://mojepanstwo.pl/mapa w serwisie nie jest wyświetlana pełna zawartość strony ponieważ z prawej strony ekranu jak również na dole nie pojawiają się "suwaki" (służące do scrollowania/przesuwania widoku). Sprawdziłem problem w trzech przeglądarkach, których używam nacodzień: Chrome (wersja 47.0.2526.80 m), Firefox (wersja 42.0) oraz Opera (wersja 34.0). Dopiero oddalenie do ok 67 % we wszystkich trzech przeglądarkach pozwala wyświetlić pełną zawartość strony. Dodam że używam netbooka z touchpadem. Piszę o tym problemie z myślą o np. osobach które mają problemy ze wzrokiem i nie są w stanie dogodnie skorzystać z serwisu przy oddaleniu/zmniejszeniu strony do 67%. Mam nadzieję, że moja uwaga przyczyni się do poprawienia jakości przydatnego i potrzebnego serwisu jakim jest mojepanstwo.pl
Pozdrawiam
Jerzy Majewski

**Comment by Cain-Ish** [comment]
Witam,
Poprosiłbym o podanie rozdzielczości ekranu oraz screen z problemem.
Dla pewności proponuje pełne przeładowanie strony przed screenem uzywając Force Refresh - CTRL+R wtedy wszelkie style zostana załadowane ponownie z naszego serwera a nie z pamięci podręcznej przeglądarki

**Comment by kokonmaster** [comment]
Witam ponownie

Pracuje na rozdzielczości 800x600. Przeładowałem za pomocą FR i ponieważ problem nadal występował zrobiłem screenshot który przesyłam w załączniku.
Pozdrawiam
Jerzy Majewski

Date: Tue, 15 Dec 2015 01:36:41 -0800

**Comment by przemo509** [comment]
Dzień dobry,

@Cain-Ish 
Jestem świadomy tego, że komentarze pod zgłoszeniami nie są odpowiednim miejscem na tego typu uwagę, ale GitHub nie posiada już funkcji prywatnych wiadomości i nie wiem jak inaczej się z Panem skontaktować. Po przeczytaniu proszę usunąć ten komentarz (nie jestem pewien czy jest taka możliwość na GitHubie).

W wielu miejscach prosi Pan użytkowników o odświeżenie strony skrótem Ctrl+R.
Niestety jest to zwykłe odświeżenie strony (w FF, IE, Chrome to to samo co F5) i nie powoduje tzw. Force Refresh, co zostało m.in. wyjaśnione tutaj:
http://superuser.com/a/205285
(oraz w komentarzach do powyższego wpisu).

Przepraszam za nadgorliwość :)
Pozdrawiam

**Comment by Cain-Ish** [comment]
Jest to słuszna uwaga - miałem na myśli CTRL+SHIFT+R który odpowiada za przeładowanie strony z pominięciem cache.
