### ISSUE TITLE
Państwo na Tweeterze - Partie polityczne

### ISSUE THREAD

**Issue by MiJas77** [epforgpl/_mojePanstwo-Portal#615]
W dziale "media" po wyborze "partie polityczne" nic się nie zmienia i dalej pozostają dane z działu głównego "Państwo na Tweeterze". Czy to przypadkiem nie jest błąd? Mam wrażenie że powinna się wyświetlać aktywnośc poszczególnych partii politycznych a tak się nie dzieje. Proszę o odpowiedź

**Comment by AsiaPrzybylska** [comment]
Link działa już poprawnie: https://mojepanstwo.pl/media/partie
