### ISSUE TITLE
API zwraca błędne dane wyszukując po numerze NIP

### ISSUE THREAD

**Issue by tikky** [epforgpl/_mojePanstwo-Portal#620]
Korzysta z API aby wyszukiwać firmę po numerze NIP.
Wszystko działało prawidłowo ale już wczoraj zauważyłem błąd.

Przy wyszukiwaniu po NIP bez znaczenia jaki wpiszę numer, API zawsze zwraca dane jednej firmy.
Jest to firma o nazwie "WART A. D. KAPICA SPÓŁKA JAWNA", KRS: 0000595143

Przykład: weźmy jakąś popularną firmę - np. Coca Cola.
NIP z ich strony (http://www.cocacola.com.pl/kontakt/dane-kontaktowe.html) to: 526-020-96-79

Wyszukuję więc za pomocą linka tego co zwykle, podając NIP bez kresek:
http://api.mojepanstwo.pl/krs/podmioty?conditions%5Bnip%5D=5260209679

...i otrzymuję dane firmy KAPICA a nie Coca Cola.

Wygląda na to, że pojawił się jakiś błąd w systemie.
Będę wdzięczny za sprawdzenie i informację zwrotną,

**Comment by jakublipinski** [comment]
@tikky też miałem ten problem. Pomogła zmiana API na v3. Używam teraz: https://api-v3.mojepanstwo.pl/dane/krs_podmioty?conditions%5Bkrs_podmioty.nip%5D=5260209679

**Comment by AsiaPrzybylska** [comment]
Prosimy o używanie API w sposób opisany przez Kube.
