### ISSUE TITLE
500-tka podczas próby resetu hasła

### ISSUE THREAD

**Issue by magul** [epforgpl/_mojePanstwo-Portal#624]
Przy próbie resetu hasła dostaję 500-tkę.

Na stronie https://mojepanstwo.pl/ wszystko zadziałało poprawnie - problem zaobserowałem przy popupie logowania do https://forum.kodujdlapolski.pl/ oraz pod https://mojepanstwo.pl:1234/ (to jest docelowy adres, do którego kieruje logowanie na forum KdP).

**Comment by KrzysztofMadejski** [comment]
@magul poprawiałem to, sprawdzisz i zamkniesz jeżeli działa?

**Comment by magul** [comment]
@KrzysztofMadejski na forum przypomnienie nie wywala już 500-tki. Na stronie http://mojepanstwo.pl:1234/ cały czas jest 500-tka.

NIe wiem do czego wykorzystujecie tę stronę - czy ona jest dostępna publicznie, czy to może jest jakiś system testowy?

Jeżeli poprawka na forum jest wystarczająca, to issue jest do zamknięcia.

**Comment by KrzysztofMadejski** [comment]
http://mojepanstwo.pl:1234/  bedzie wylaczane
