### ISSUE TITLE
Strona główna ładuje mi się 20s

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-Portal#627]
Konsola podpowiada, że to przez wczytywanie tapety i synchroniczne wywołanie skryptu js.

![bug-mp](https://cloud.githubusercontent.com/assets/849975/12873626/bc8d67e0-cdc2-11e5-9e29-df785d75236b.PNG)

**Comment by Cain-Ish** [comment]
Nowy layout nie posiada juz background wiecproblem został "po części" rozwiazany
