### ISSUE TITLE
Strona błędu HTTP500

### ISSUE THREAD

**Issue by kubamarchwicki** [epforgpl/_mojePanstwo-Portal#636]
Dostaję pińcset na https://mojepanstwo.pl/dane/zamowienia_publiczne/2676148/dokumenty/2700777 (próbując podejrzeć przetargi IPNowe).
To skłoniło mnie do zastanowienia, może strona błędu powinna linkować do https://mojepanstwo.pl/pomoc/zglos_blad lub od razy informację jak zgłosić błąd wrzucała na stronę, albo od razu tworzyła linka do github issue w takiej formie `https://github.com/epforgpl/_mojePanstwo-Portal/issues/new?title=Błąd HTTP{kod} na stronie&body={url}`

Takiego URLa po stronie przeglądarki można wygenerować? Chyba że błędzie wiecie i zgłoszenia są zbyteczne ;-)

pozdrosy

**Comment by Cain-Ish** [comment]
Widze że problem jest już rozwiązany. Sugestie przekaże dalej.Pozdrawiam
