### ISSUE TITLE
Uzupełnianie konta bankowego - ucina początkowe zero!!

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-Portal#638]
Edytując profil NGO wpisałem numer konta bankowego jako "05 2130 0004 2001 0629 8111 0001"

Ucięło mi początkowe zero i pojawiło się "5213000042001062981110001"

BTW: Nie mogę edytować tego numeru konta po dodaniu.

**Comment by MarekBielecki** [comment]
Już nie ucina początkowego zera. Co do edycji jest ona możliwa dopiero po odrzuceniu lub zaakceptowaniu konta przez administratora. Teraz odrzuciłem podane przez Ciebie wcześniej konto i możesz je poprawić.
