### ISSUE TITLE
Brak strony z twitami poszczególnych użytkowników

### ISSUE THREAD

**Issue by jklawiter** [epforgpl/_mojePanstwo-Portal#641]
Na stronie https://mojepanstwo.pl/media można kliknąć w poszczególnych komentatorów aby otworzyć ich strumień TT, jednak zamiast tego strumienia otwiera się po prostu pusta strona i nic się dalej nie dzieje. 

np taki link: https://mojepanstwo.pl/dane/twitter_accounts/1212 

$ curl https://mojepanstwo.pl/dane/twitter_accounts/1212
[wariat@grab ~]$

**Comment by danielmacyszyn** [comment]
Poprawione - usunięto omyłkowo pozostawiony kod testowy
