### ISSUE TITLE
Problemy z API do BDL na MojePanstwo

### ISSUE THREAD

**Issue by pbiecek** [epforgpl/_mojePanstwo-Portal#642]
Nie działa API do pobierania danych z BDL
https://mojepanstwo.pl/api

np. nie działa
https://api-v3.mojepanstwo.pl/dane/bdl_wskazniki/720
(zwraca puste dane)

**Comment by pbiecek** [comment]
@danielmacyszyn @Cain-Ish Czy jest jakiś postęp w tym temacie?

**Comment by pbiecek** [comment]
@danielmacyszyn @Cain-Ish Czy jest jakiś postęp w temacie dostępu do BDL?

**Comment by vindemi** [comment]
Podpinam się pod pytanie

**Comment by KrzysztofMadejski** [comment]
Pośrednio dzięki działalności rzeczniczej Fundacji, a bezpośrednio dzięki zaangażowanemu zespołowi Ministerstwa Cyfryzacji i GUS, BDL posiada już własne oficjalne API: https://api.stat.gov.pl/
Polecamy skorzystać z niego.
