### ISSUE TITLE
Bank Danych Lokalnych się popsuł?

### ISSUE THREAD

**Issue by d33tah** [epforgpl/_mojePanstwo-Portal#654]
Zerknijcie tutaj:

https://mojepanstwo.pl/dane/bdl_wskazniki/438,apteki-lacznie-zakladowymi

U mnie nie ma tu żadnych danych ani możliwości wyboru gminy. Jeżeli to nie błąd mojej przeglądarki, może przydałby się jakiś komunikat błędu?

**Comment by KrzysztofMadejski** [comment]
Pośrednio dzięki działalności rzeczniczej Fundacji, a bezpośrednio dzięki zaangażowanemu zespołowi Ministerstwa Cyfryzacji i GUS, BDL posiada już własne oficjalne API: https://api.stat.gov.pl/
Polecamy skorzystać z niego.
