### ISSUE TITLE
Problem z dostępnością/wydajnością API v3 (timeouts)

### ISSUE THREAD

**Issue by alex-kowalczyk** [epforgpl/_mojePanstwo-Portal#676]
Dzień dobry,
Czy odnotowują dziś Państwo jakieś problemy z serwerami API v3? Duży odsetek zapytań kończy się błędem (timeout). 
Czy jest znana jakaś prognoza terminu polepszenia sytuacji? 
Pozdrawiam!

**Comment by danielmacyszyn** [comment]
Tak. Mieliśmy wczoraj problemy z jednym z serwerów. Zostało to już naprawione i teraz wszystko powinno działać stabilnie. Przepraszamy za problemy.

**Comment by alex-kowalczyk** [comment]
@danielmacyszyn  Dziękuję!
