### ISSUE TITLE
nieaktualne dane Projekt Wielka Zmiana KRS 552624

### ISSUE THREAD

**Issue by maciek1985** [epforgpl/_mojePanstwo-Portal#752]
Dzień dobry,

Podmiot Projekt Wielka Zmiana został wykreślony decyzją sądu z KRS dnia 11.04.2017. Proszę o usunięcie danych podmiotu z serwisu, w szczególności adresu firmy, do którego Projekt Wielka Zmiana nie ma już prawa korzystać. 

Poniżej treść komunikatu z MSiG, który mówi o wykreśleniu. 

Maciej Wójcik

PROJEKT WIELKA ZMIANA SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ W LIKWIDACJI (KRS 0000542624)
20 kwietnia 2017 - MSiG nr 77/2017 - WPISY DO KRAJOWEGO REJESTRU SĄDOWEGO - Kolejne - Spółki z ograniczoną odpowiedzialnością
W dniu 11 kwietnia 2017 r. wykreślono z rejestru KRS wszystkie wpisy dla tego podmiotu.

**Comment by danielmacyszyn** [comment]
Proszę o kontakt w tej sprawie na adres daneosobowe@mojepanstwo.pl
Dziękuję
