### ISSUE TITLE
Nie można obejrzeć Monitora Sądowego i Gospodarczego

### ISSUE THREAD

**Issue by tomchal** [epforgpl/_mojePanstwo-Portal#753]
Nie można obejrzeć Monitora Sądowego i Gospodarczego:

https://mojepanstwo.pl/dane/msig/5184

Podobna sytuacja jest w wielu innych miejscach serwisu - np. orzeczenia sądów administracyjnych czy powszechnych...

![obraz](https://cloud.githubusercontent.com/assets/16117454/26486048/d2e07da0-41f9-11e7-9c4f-9129251cc96a.png)

**Comment by danielmacyszyn** [comment]
Poprawione
