### ISSUE TITLE
Traffic Deal Sp. z o.o.

### ISSUE THREAD

**Issue by TrafficDeal** [epforgpl/_mojePanstwo-Portal#764]
Dear All,

please note that since 15.12.2016 traffic deal sp. z o.o. is belong to Technotop and has a new registered address: ul. Kościuszki 33 lok 213, 05-500 Piaseczno.

If you have any questions please do not hesitate to contact with me.

Best regards,
Traffic Deal Sp. z o.o.

**Comment by danielmacyszyn** [comment]
Updated
