### ISSUE TITLE
API BDL szczegoły nie zwraca rezultatów.

### ISSUE THREAD

**Issue by tomchal** [epforgpl/_mojePanstwo-Portal#768]
Witam;

Próbuję skorzystać z API dla BDL, ale dowolne zapytanie o dane szczegółowe zwraca błąd. (Również te które są podane jako przykłady):

// 20171012144813
// https://api-v3.mojepanstwo.pl/bdl/series?metric_id=762

{
  "code": "API_BDL_INVALID_INPUT",
  "params": {
    "param": "metric_id"
  },
  "message": "API exception occurred"
}

**Comment by vindemi** [comment]
Również podpinam się pod problem. Nie działają takie zapytania jak:
https://api-v3.mojepanstwo.pl/dane/gminy
lub
https://api-v3.mojepanstwo.pl/dane/gminy/2024?fields[]=gminy-dochody-dzialy&fields[]=gminy-wydatki-dzialy

@danielmacyszyn 
@KrzysztofMadejski 

Czy ktoś może postawić ponownie działające API?

**Comment by KrzysztofMadejski** [comment]
Przepraszamy za zaistniałe problemy. Będziemy przebudowywać mojepaństwo, więc pełne dane pojawią się zapewne dopiero w nowej odsłonie serwisu.

**Comment by vindemi** [comment]
Dziękuję za odpowiedź. Jest jakiś graniczny termin wprowadzenia tych zmian? Struktura API zostanie mocno przebudowana? Na tym API oparłem temat mojej pracy magisterskiej, a chciałbym skończyć ją pisać do końca tego miesiąca.

**Comment by KrzysztofMadejski** [comment]
Niestety nie wiem. @danielmacyszyn zarządza projektem.

**Comment by patkru** [comment]
+1, czy wiadomo coś nt. przybliżonego terminu realizacji?

**Comment by KrzysztofMadejski** [comment]
Pośrednio dzięki działalności rzeczniczej Fundacji, a bezpośrednio dzięki zaangażowanemu zespołowi Ministerstwa Cyfryzacji i GUS, BDL posiada już własne oficjalne API: https://api.stat.gov.pl/
Polecamy skorzystać z niego.
