### ISSUE TITLE
Żądana strona jest obecnie niedostępna.

### ISSUE THREAD

**Issue by davesingh1** [epforgpl/_mojePanstwo-Portal#776]
Po wejściu wyszukanej spółki otrzymuję poniżej błąd:

Żądana strona jest obecnie niedostępna.

**Comment by danielmacyszyn** [comment]
Problem wynikał z niedostępności jednego z serwerów. Mieliśmy problem z hostingiem. Strony już działają. Przenosimy serwery gdzie indziej.
Przepraszamy za problemy.
